### ISSUE TITLE
Key Partners

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#1]
Who are our Key Partners?
Who are our key suppliers?
Which Key Resources are we acquiring from partners?
Which Key Activities do partners perform?

**Comment by bdshanks-28** [comment]
Who would be key partners?
Key suppliers might be the databases we use as sources?
Key resources would be the databases.
Key activities for partners to do?

**Comment by Cade5480** [comment]
Our Key Partners are Slack, GitHub, Swift, and SQL Server. We will be using these companies applications to assist in creating our app.

Our Key Supplier is USADA, they are going to provide the information that we need in order to correctly store the information for the macros.

**Comment by Cade5480** [comment]
So our key resources are gonna be software/applications will be Slack, GitHub, Swift, and Microsoft SQL Server

**Comment by Cade5480** [comment]
We are choosing our Key Partners for a reason, they provide needs for us that are more suitable than competitors. Slack offers a free way to communicate professionally. GitHub allows us to create a quick and easy repository for us to commit to. Swift is going to allow us to program for free and be the most compatible with creating an application. Finally, Microsoft SQL Server is a free quick and easy way to create databases and is compatible with Swift.

**Comment by aaleksandraristic** [comment]
Should we add some partners who will help to reach users and promote our app? 

e.g. Partners such as fitness influencers, gyms, and health educators whose content is published online
       *Usually, it's easier to reach Instagram and other social media influencers than big companies to support and work with us.
 
(I guess this doesn't have to be that realistic, but the point is to make it as we would like it to develop and make money out of it) What do you think about that?

**Comment by IanTDuncan** [comment]
Could Key Partners also include those who make the recipes themselves? This could also include the consumer/customer if we allow them to submit recipes too.

**Comment by BeepDroid** [comment]
What is the distinction between Key Partners/Key Suppliers, if I may ask?

**Comment by bdshanks-28** [comment]
How would we reach out to partners?

**Comment by Cade5480** [comment]
I definitely think we can reach out to other partners such as Instagram, that way our app can have some publication that a broad audience can see. 

I also very well think our customers can be considered key partners as well. If they are able to create their own meal or recipes, then they provide us with a source of what food is eaten the most.

The distinction between our Key Partners and Key Suppliers is that our partners are going to be those companies that provide us the needs to create this app and our suppliers are gonna be those who give us the information to store in our database to be used in our app. 

To reach out to these partners we can use the most appropriate way of communication whether that be through email or other professional outlets.

I hope you all agree with these solutions to some of your questions, let me know what you think!

**Comment by bdshanks-28** [comment]
Sorry I realized reaching our partners fell more on channels, so really that answer mostly relies on proper channels.

**Comment by aaleksandraristic** [comment]
I think this looks great! The only thing I am still rethinking is Key Partners. In my opinion, it is not just partners who are providing us needs to create the app, but also the ones who are promoting it, like marketing companies or people, and some other partners who are involved in our business to help it fully succeed. What do you think about that? Please, tell me if I am wrong, I am just not sure what we should be considering as key partners. @Cade5480

**Comment by Cade5480** [comment]
So the definition of Key Partners is going to be any person or company that we rely on to achieve our application, so this is going to be pretty much any company that we rely on to supply us with the required software to create our app! As far as promoting goes, Channels answers that question of how promotion will not come until after we have reached out to our friends, family and acquaintances first, then proper advertisement can ensue from there.

**Comment by aaleksandraristic** [comment]
Hmm yeah, that makes sense, thanks for the explanation! We can close this issue and I will add it to the Business Canvas Model.
