### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by IanTDuncan** [IanTDuncan/MealTime#10]
Through which Channels do our Customer Segments 
want to be reached? 
How are we reaching them now?
How are our Channels integrated? 
Which ones work best?
Which ones are most cost-efficient? 
How are we integrating them with customer routines

**Comment by bdshanks-28** [comment]
I got this

**Comment by IanTDuncan** [comment]
@bdshanks-28 This is all on you. No pressure. :)

**Comment by bdshanks-28** [comment]
Fix to issue 1: We would have to reach out through a mobile app store such as Apple App store or Google Play.
2: We would have to spread through word of mouth and start with friends and family and spread there. If we have a bigger budget, proper advertising could be done.
3: Currently don't understand.
4. Currently don't understand.
5. Not sure I understand correctly
6. Google Play store would do best since it is cheaper to throw out into the market.
7. Do not understand at this time.

**Comment by bdshanks-28** [comment]
Question 2: How are we reaching them now?

Simple. We are not reaching them at all. We should go on and speak to our friends and family first to at least get a starting base of customers to spread to. Then once we get that, we can look for proper advertising.

**Comment by bdshanks-28** [comment]
How do our channels integrate with our customer segments?

By doing Face-to-Face channels, we can try and get our foot in the door of these niche markets. Once we get an entrance, we could easily switch our primary focus being Internet/Social-media as our channel to integrate with our customers. A niche market would become more spread if we can get an online presence.

Thoughts?

**Comment by Cade5480** [comment]
I agree, i think face to face channels will be more beneficial than any other option, looking good so far Brandon!

**Comment by BeepDroid** [comment]
An online presence would definitely help out. Down the line we could develop a main website to extend the reach even further, allow for signups through that portal, gradually move out of simply app based and get more users across the country/world/wherever there may be people.

**Comment by BeepDroid** [comment]
Also, as our customer segment model seems to be more geared towards the psychographic (lifestyle-type stuff) model, we could find more channels through that. Maybe blog/vlog type stuff?

**Comment by IanTDuncan** [comment]
I agree with Kerry, we definitely need some sort of online presence. Other than that everything looks good!

**Comment by bdshanks-28** [comment]
I'm redoing my first issue. Through which do we want to reach our customers?

I had misunderstood the question initially but now I understand it. How we would reach our customer segments would be something like a social media account for marketing and word of mouth. That would probably be how they would want to be reached.

**Comment by bdshanks-28** [comment]
Redoing the second Question: How are we reaching our customer segments?

Again, I will say as of right now, we are not reaching out through any channels right now. Perhaps I should go ahead and create a business email to sign up for social media platforms to have that ready to go when we have something to show off?

Thoughts?

**Comment by bdshanks-28** [comment]
Which ones work best?
     Easily, a social media presence is the best working channel in theory. You can reach a wider audience than if you had just remained on face-to-face terms

Which ones are most cost-efficient?
    Social media is free as a start. Though if we want more of a presence there are paid features to get more ads out and even show up in recommended tabs more often. Face-to-face would require material to hand out and show off to make them remember the product, so it is more cost heavy.

How are we integrating them with customer routines?
     Typically, if we go the social media route, a morning post would integrate well into breakfast routines, a noon post would be good for lunch time, and an evening post could do well to integrate into dinner routines. More posts throughout the day may line up with snacks the customer might have as part of their routine, but placed perfectly in between the 3 main posts to hopefully get into their routines.

**Comment by BeepDroid** [comment]
Everything looks good!

**Comment by Cade5480** [comment]
I agree with Kerrigan, everything looks ship shape!

**Comment by IanTDuncan** [comment]
Everything looks great!

**Comment by aaleksandraristic** [comment]
> Question 2: How are we reaching them now?
> 
> Simple. We are not reaching them at all. We should go on and speak to our friends and family first to at least get a starting base of customers to spread to. Then once we get that, we can look for proper advertising.

Should we add here like marketing companies and other paid partners who are going to promote our app? I guess we want to represent the best possible picture or option for our brand to succeed (even if we are not actually going to pay in real life)? What do you think? @BeepDroid @Cade5480 @bdshanks-28 @IanTDuncan

**Comment by bdshanks-28** [comment]
From what I was reading, that is where ad promotions would go, but seeing as we have none, I just did not mention that as an option. Word of mouth and social media presence would probably be the best for us anyways since it helps tie in with what our targeted market is.

**Comment by aaleksandraristic** [comment]
Yeah, that makes sense! Everything looks great! We can close this issue.
