### ISSUE TITLE
Removal of privacy_security_policy_activity.xml

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#108]
Removal of privacy_security_policy_activity.xml
------------------------------------

Description: 
----------------------------

Found that this page's purpose conflicted with the newly renamed "policies_about_activity.xml". A mistake because of poor naming of the initial page that did not make the purpose clear at the time.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

Operating System: Android
Kotlin Version: 1.5.21
Android Studio Version: 4.2.1
Gradle Version: 7.0.2

For Issue Resolution:
------------------------------

The removal of "Privacy_security_policy_activity.xml". Informing Cade so his backend code can reflect this changes.

For Investigations/Research:
------------------------------------------

A review of all pages and their purposes revealed this issue. Discussed with Aleks and Cade about it before moving on to delete this.

Current Status: 
------------------------

In progress

**Comment by bdshanks-28** [comment]
@Cade5480 Be aware that privacy_security_policy.xml will NOT be the main page I will work on for the display of hyperlinks to our policies. Instead that will become **policies_about_activity.xml**.

**Comment by Cade5480** [comment]
Same as the others, I do not think we will use this activity due to the fact that our privacy policy is in our About section in the my account.
