### ISSUE TITLE
Customer Segments

### ISSUE THREAD

**Issue by BeepDroid** [IanTDuncan/MealTime#11]
For whom are we creating value?
Who are our most important customers?
_Mass Market
Niche Market
Segmented
Diversified
Multi-sided Platform `_

**Comment by BeepDroid** [comment]
This is mine to do, all mine

**Comment by BeepDroid** [comment]
The market we would be creating value for and targeting would be the **niche market**, as the application is geared towards those with budgets and interest in meal prep.

**Comment by Cade5480** [comment]
Not much to comment on, everything looks good so far!

**Comment by bdshanks-28** [comment]
Why exactly niche? What's with segmented and diversified? Sorry, I'm not clear on those, I just wanna clarify so I more understand why we are aiming for the niche market.

**Comment by BeepDroid** [comment]
There are 8 main customer segmentation models, and we should find which fits our target customer base best. These are:

**Demographic** - Population-related characteristics such as income, education level, gender, and age. The various demographic characteristics can be used together to create segmented customer groups, most useful to brands that sell a variety of products. 

**Geographic** - Geographic segmentation in marketing entails categorizing an audience base by location. These categories can be broad or narrow, depending on the data you're trying to gather. Some examples of categories by which you might separate your audience include country, time zone, region, state or city.

**Behavioral** - Behavioral segmentation groups consumers together by habits and behaviors, rather than external demographic factors. For example, purchase history and preferred social media platform usage.

**Psychographic** - Psychographic segmentation dives even deeper into the internal workings of your consumers by grouping them together based on psychological characteristics, including personality, habits, beliefs, and interests. Great for lifestyle brands that want to align themselves with consumers who live or aspire to live the lifestyle that the brand promotes.

**Technographic** - Technographic segmentation lets you target consumers that use different types of software or online services in a highly personalized fashion.

**Firmographic** -  Creating subgroups simply around the decades or eras into which your consumers were born.

**Needs-Based** - Needs-based segmentation involves segmenting customers into groups based on their problems and needs.

**Values-Based** - Needs-based segmentation involves segmenting customers into groups based on their problems and needs.

I feel as though our customer model fits more into either **Needs-Based** or **Psychographic** , but does anyone else have any thoughts or input?

**Comment by BeepDroid** [comment]
@bdshanks-28 Good question! Segmented refers to the different customer segment models, those of which I just now listed for you guys to browse. As for the niche market, it can be described with "a very specific segment of consumers who share characteristics and, because of those characteristics, are likely to buy a particular product or service." While our product could benefit many, it's more suited for the niche market as we are targeting those with an interest in health **and** those with a limited budget. This puts a focal lens on what would otherwise be the mass market. As for diversified, it's how we'll expand our reach and include more customers with more needs.

**Comment by bdshanks-28** [comment]
@BeepDroid Thanks for clarifying, doing great!

**Comment by BeepDroid** [comment]
Considering how our service works, we are not a **multi-market platform**, as we do not depend on a secondary segment to keep the application running. An example of this is like Ebay or community market applications who depend on buyers, sellers, and secondary bank transactions. Any other thoughts on this?

**Comment by IanTDuncan** [comment]
**I actually disagree with us not being a multi-market platform.**My reason is that the meals and recipes we generate have to be pulled from sources otherwise the foods we suggest will be a chaotic slurry of ingredients. If I'm wrong about any of this please let me know!

**Comment by bdshanks-28** [comment]
Does this mean we are pulling from recipes on the internet? Do our suppliers expand then? How do we go about giving credit to the original cooks of that recipe?

**Comment by BeepDroid** [comment]
That is completely my bad; I misunderstood what multi-platform meant. I thought it was strictly about **marketing** and purchasing with secondary applications, but I very much was wrong. We ARE a multi-platform application as we have several partners providing information, you are completely right @IanTDuncan . And @bdshanks-28 my thinking was we could pull from the internet, as there are a LOT of websites with long lists of recipes, and we could credit the original cook in the recipe page. That's just a stray thought that will absolutely need refinement. Another idea was using AI (if possible? Not a great fan of it but perhaps an option) to generate meals based on the ingredients we take from the US website. 

Either way, it will all still qualify as **multi-platform**.

**Comment by bdshanks-28** [comment]
Right we can finalize the idea there later, but this issue is still solved I think.

**Comment by Cade5480** [comment]
Reading through everything looks good! We can maybe look into closing this issue soon.

**Comment by aaleksandraristic** [comment]
Sorry, I am kinda lost here. I can't recognize the most important things that I should put in a Canvas Model. Could you please help me with it?

**Comment by BeepDroid** [comment]
> Sorry, I am kinda lost here. I couldn't recognize which are the most important points that I should put in a Canvas Model. Could you please help me with it? @BeepDroid

Of course! So, the most important things are: 
We are selling for a **niche market**.
We have a **psychographic** (AKA lifestyle based customer model).
We are **multi-platform**.
And, as for diversified, we can explore options related to fitness and more health, to keep in touch with our customer model.

I believe that answers all the points!

**Comment by aaleksandraristic** [comment]
Yaaas, thank you so much!! I will add this to Business Canvas Model!
