### ISSUE TITLE
Look at removing options_activity.xml

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#115]
Look at removing options_activity.xml
------------------------------------

Description: 
----------------------------

Look to remove this file as it is redundant with account_options_activity.xml issue #104. Must discuss with Cade in reference to issue #95.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

Operating System: Android
Kotlin Version: 1.5.21
Android Studio Version: 4.2.1
Gradle Version: 7.0.2

For Issue Resolution:
------------------------------

Discuss with @Cade5480 for backend development to remove this file without messing up any existing code he has put in for functionality.

For Investigations/Research:
------------------------------------------

Discuss with team if the purpose of this file overlaps with my_account_activity.xml and look to remove this.

Current Status: 
------------------------

In progress

**Comment by Cade5480** [comment]
I took a look at this this morning and we can do away with this activity as I do not think we will need it now or down the road

**Comment by bdshanks-28** [comment]
Alright. Double checking though, no code is tied to this correct?
