### ISSUE TITLE
API - Edmamam Shopping List - ShoppingSearchResult Class

### ISSUE THREAD

**Issue by BeepDroid** [IanTDuncan/MealTime#117]
### API - Edmamam Shopping List - ShoppingSearchResult Class
________________________
### Description:
_______________________
The ShoppingSearchResult class serves as a data model to represent individual search results obtained from an API. In the context of the provided code examples, the class is designed to encapsulate information about items in search results, such as their names and prices.

### Steps to Reproduce:
__________________________

1. Decide on the properties you're going to need for this class. 
2. Create the ShoppingSearchResult java class in the same folder as the rest of our classes as our handler class is going to be referencing it. 
3. Definte the class and properties, code snippet example will be provided.

### Expected vs. Actual Behavior:
__________________________
Expected: Capture and encapsulate the data pulled from our API call.

Actual: Having some trouble with the API logic. 

### Code Snippets:
_______________________
`private String itemName;
        private double itemPrice;
        private int servings;

        //Will add more properties as needed

        public ShoppingSearchResult(String itemName, double itemPrice) {
            this.itemName = itemName;
            this.itemPrice = itemPrice;
        }

        public String getItemName() {
            return itemName;
        }

        public void setItemName(String itemName) {
            this.itemName = itemName;
        }

        public double getItemPrice() {
            return itemPrice;
        }

        public void setItemPrice(double itemPrice) {
            this.itemPrice = itemPrice;
        }

        public int getServings(){
            return servings;
        }

        public void setServings(int servings){
            this.servings = servings;
        }`

### Environment Details:
____________________________
Android Studio compiler, Windows OS. 

### Current Status:
______________________________
In progress

**Comment by aaleksandraristic** [comment]
Hey Kerry, I see that you are working on this issue. Could you please just update the due date in the roadmap for it? Put the date that you expect to finish it.
