### ISSUE TITLE
Business Canvas Model Information

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#12]
![image](https://github.com/IanTDuncan/MealTime/assets/143129097/13551f53-f4e0-4e5e-a24c-6e61bef7c80f)

**Key Partners #1** (CLOSED)
1.Who are our Key Partners?
Our Key Partners are Slack, GitHub, Swift, and SQL Server. We will be using these companies’ applications to assist in creating our app. We will also be using the google play store to upload our app onto android.

2.Who are our key suppliers?
Our Key Supplier is USADA, they are going to provide the information that we need in order to correctly store the information for the macros.

3.Which Key Resources are we acquiring from partners?
So our key resources are going to be software/applications will be Slack, GitHub, Swift, and Microsoft SQL Server

4.Which Key Activities do partners perform?
We are choosing our Key Partners for a reason; they provide needs for us that are more suitable than competitors. Slack offers a free way to communicate professionally. GitHub allows us to create a quick and easy repository for us to commit to. Swift is going to allow us to program for free and be the most compatible with creating an application. Finally, Microsoft SQL Server is a free, quick and easy way to create databases and is compatible with Swift.
We can reach out to other partners such as Instagram, that way our app can have some publication that a broad audience can see. Our customers can be considered key partners as well. If they are able to create their own meal or recipes, then they provide us with a source of what food is eaten the most.
The distinction between our Key Partners and Key Suppliers is that our partners are going to be those companies that provide us the needs to create this app and our suppliers are going to be those who give us the information to store in our database to be used in our app.
To reach out to these partners we can use the most appropriate way of communication whether that be through email or other professional outlets.

**Key Activities #2** (CLOSED)
Key Activities our Value Propositions require
Key activities are the key things our app do to deliver value propositions to the customer. These will be noted below.
1.	An In-app calorie tracker
2.	A "grocery list" of foods and ingredients
3.	A meal planner
By keeping all these features up to date and working with each other our customers will be satisfied and a long-term relationship will slowly grow.
Distribution Channels
•	MealTime will be distributed via the internet through one of the app stores
•	The app store we will be focused on will be Android due to cost-saving and experience
Revenue Streams
•	Our revenue steam will be a free app with ads
•	Users will be able to get rid of ads by paying a small monthly subscription
Customer Relationship
•	The relationships we will have between us and our customers will be based on self-service and automated service
•	Since our app is mainly used by the customer with little to no input from us, it will be primarily automated to plan meals

**Customer Relationships #3** (CLOSED)
1.What type of relationship does each of our Customer Segments expect us to establish and maintain with them?
The customer segment model (market and initial segment model determined for right now) - self-service type of relationship. IKEA is a fantastic example of this; they give you the parts, and you build it yourself. We provide our customers with the ingredients, instructions, and health-related information, and it's up to them to prepare the actual food and stick to the generated plan.

2. Which ones have we established?
None

3. How are they integrated with the rest of our business model?
Regarding how we will be integrating our customer base into our business model, as this is a self-service relationship, we will integrate them by providing them with the means to store the data they receive. For example, should we decide to do a login function, the user can store their data, bookmarked meals, etc quite easily, making their lifestyle all that more attainable and accessible. Our main goal here is the retention of customers, not just acquisition, something we achieve with the services we offer.
Customer retention is ensuring we are giving them enough, with easy access, to not only keep them using the service, but to prompt the idea of them paying for it/subscribing to a monthly charge.

4. How costly are they?
As for cost, it depends on how many users we have to store. Should we amass a good amount of them, the cost will depend on how many are online at one time and actively using the service. We may be looking at $84 yearly -- this is based off a hosting service I use for a website I host. The more users and activity we expect, the more expensive. But just for starting out, we're likely just looking at 60-80 a year.
Also, side-note, depending on if we decide on subscription based or one-time payments for our revenue, it will between long-term (subscription based) and transactional (one-time payment) as added to the expected relationships with customers.

**Key Resources #4** (CLOSED)
Key Resources our Value Propositions require
Key resources are what allow our app to function effectively, I will outline the ones we have below.
1.	Food nutrition information/data which will be pulled from [FoodData Central](https://fdc.nal.usda.gov/) which is maintained by the USDA
2.	The app itself, contains the systems our customers will use to plan their meals
3.	Our database of meals, will be used by the customer
Distribution Channels
•	MealTime is an app designed for "want" rather than "need" and will be focused on a niche, lifestyle market.
•	Our product will be a standard one, mainly sold through the various mobile app stores to help reach a wide audience.
Revenue Streams
•	Our revenue steam will be a free app with ads
•	Users will be able to get rid of ads by paying a small monthly subscription
Customer Relationship
•	Since customers will be able to input their own meals and recipes they will be able to share with other MealTime customers, this will be a co-creation relationship
•	In time we hope to grow a community based on these customer inputs which will lead to a long-term relationship

**Value Propositions #5** (CLOSED)
We will be delivering an option to our customers to track their caloric intake along with other macros through our application.
We are making a solution for our customers to be able to lose weight by eating healthier.
We are offering a calorie tracker, a grocery list to view certain foods and be able to choose and select which ones you have consumed as well as generate a meal for you along with the calories and other macros all through our application.
Our team will be satisfying the needs of people who wish to track their caloric intake and people who wish to live a healthier life as well as satisfy the needs of people who do not want to get pulled into a monthly calorie tracker subscription.

**Cost Structure #6** (CLOSED)
1. What are the most important costs inherent in our business model?
Answer:
Fixed costs - These are costs that remain relatively constant.
* Publishing and keeping an app on the Google Play Store for Android (monthly/yearly)
* Salaries for employees
* Utilities such as internet, available software, electricity
Variable costs - These costs fluctuate.
* Raw data resources - availability...
* App development costs - development, updating, editing, design...
Operating costs - These are ongoing expenses essential for running the day-to-day operations.
* Marketing and Advertising - promotions and attract the app visibility
* Research and Development - developing new features; improving existing ones
* IT Infrastructure - costs associated with maintaining computer systems and software
Unpredictable costs - costs that might appear in the future
________________________________________
2. Which Key Resources are most expensive?
Answer:
Human Resources - people power
*Employees - software engineers, data analysts, project manager
*Key Partners - USADA, ...
Financial Resources - provide the necessary capital for developing and maintaining the app
*Investments, grants, lines of credit
*Branding – design, logo, graphics
*App Store Hosting - Google Play Store
*Employees – money for salaries, tax, healthcare…
*Marketing – B2C (business to customer) and market sector (food, health track, time-saving app)
*Raw Data – for now, we are using free public data that we have found on the Internet, but there is a threat if the access
becomes limited then we have to pay for it.
Intellectual Resources - These are intangible resources like:
*If we develop some innovative idea/feature we could get our own patent
*We have our own brand - MealTime
*Partnerships
Digital Resources
*Software/applications - Slack (communication), GitHub, Swift, and Microsoft SQL Server + ... (maybe something else)
*Online Data Source - USADA
________________________________________
3. Which Key Activities are the most expensive?
Answer:
Research and Development
*Research and development of the app features
*Updates of the existing version
*Quality checks - both frontend (software development check) and backend (data quality check)
*Cost checks - we want to reduce or minimize costs and to achieve a goal
*Design cost
Problem Solving - finding a solution to individual problems faced by both customers and developers
* Project Management
* Data Cleaning and Analysing
* Software Development
* Testing
Platform/Network - networks, combination platforms, software.

**Revenue Streams #9** (CLOSED)
1. For what value are our customers really willing to pay?
value = features
Answer:
Customers are generally willing to pay more for the following features:
•	time savings
•	recommendations
•	high-quality (no errors or bugs)
•	easy-to-use
•	well organized
•	fast
•	well-designed (good app interface)
•	good-featured mobile apps
•	most popular app (we need a good marketing plan)
•	user loyalty
•	personalization plan
•	good/positive reminders/notifications (no spam notifications)
•	easy connection with other apps on their devices (integration with fitness trackers )
•	offline app
•	freedom in designing (mostly women like to design the interface on their own)
•	lower price/subscription
•	privacy safety.
*The more demand there is for something, the more people will be willing to pay for it.
Problem: We have a lot of competitors on the market with similar apps which also means that the supply on the market is really high. With a high supply on the market, there is a low demand and lower price that customers are willing to pay.
* Find a way to reach the customers, if not by price, maybe with some features that other apps offer at higher prices or so.
________________________________________
2. For what do they currently pay?
Users currently pay for similar apps that provide comprehensive meal planning and nutrition tracking services. These apps typically offer free basic versions and premium versions with advanced features such as custom meal plans, access to a larger food database, and the removal of ads. Users are willing to pay for the convenience of having all their nutrition and meal planning needs in one place.
________________________________________
3. How are they currently paying?
Answer:
•	Subscription Model - offer free content in their apps for a limited amount of time and then charge users a subscription fee that will allow them to access full content without any restrictions. Subscription-based apps charge users a recurring fee in exchange for access to exclusive content and premium features and services. The fee is often a monthly or yearly subscription, but can also be chargeable weekly or quarterly. When a subscription period ends, users can cancel or modify their subscriptions. But in some cases, the subscription may automatically renew.
Subscriptions provide users with ongoing access to premium features, often with monthly or yearly billing options. Some users may also opt for free versions with ads.
•	In-App Purchases Model - distributed to access the powerful and advanced features to allow much swifter and empowered user interaction. Apps with in-app purchases generate the highest app revenue for their publishers. Overall, this is an interesting model for converting non-paying app users into paying users without being too intrusive. However, you’ve to keep users hooked on your free mobile apps so that they keep paying. In-app purchases allow users to unlock specific features or remove ads on a one-time basis.
________________________________________
4. How would they prefer to pay?
Users may prefer flexible payment options, including both one-time purchases and subscription models. Offering a free version with ads and limited features, along with a premium subscription that unlocks additional benefits, would cater to a wider audience. Additionally, providing various subscription durations (e.g., monthly, yearly) allows users to choose based on their preferences and commitment level.
________________________________________
5. How much does each Revenue Stream contribute to overall revenues?
Initially, one-time purchases may contribute a significant portion of revenue as users try out the app and decide to unlock specific features. However, over time, subscription revenue is likely to become a more substantial part of the overall revenue as users value the ongoing benefits of a premium subscription. Advertising revenue may also play a role, particularly for users who prefer to use the free version supported by ads.

**Channels #10** (CLOSED)
1.Through which Channels do our Customer Segments want to be reached?
We would have to reach out through a mobile app store such as Apple App store or Google Play.
2. How are we reaching them now?
Social media accounts for marketing and word of mouth. That would probably be how they would want to be reached. Word of mouth and social media presence would probably be the best for us anyways since it helps tie in with what our targeted market is.
3.How do our channels integrate with our customer segments?
By doing Face-to-Face channels, we can try and get our foot in the door of these niche markets. Once we get an entrance, we could easily switch our primary focus being Internet/Social-media as our channel to integrate with our customers. A niche market would become more spread if we can get an online presence.
4.Which ones work best?
Easily, a social media presence is the best working channel in theory. You can reach a wider audience than if you had just remained on face-to-face terms
5.Which ones are most cost-efficient?
Social media is free as a start. Though if we want more of a presence there are paid features to get more ads out and even show up in recommended tabs more often. Face-to-face would require material to hand out and show off to make them remember the product, so it is more cost heavy.
6. How are we integrating them with customer routines?
Typically, if we go the social media route, a morning post would integrate well into breakfast routines, a noon post would be good for lunch time, and an evening post could do well to integrate into dinner routines. More posts throughout the day may line up with snacks the customer might have as part of their routine but placed perfectly in between the 3 main posts to hopefully get into their routines.

**Customer Segments #11** (CLOSED)
The market we would be creating value for, and targeting would be the niche market, as the application is geared towards those with budgets and interest in meal prep. As for the niche market, it can be described as "a very specific segment of consumers who share characteristics and, because of those characteristics, are likely to buy a particular product or service." While our product could benefit many, it's more suited for the niche market as we are targeting those with an interest in health and those with a limited budget.
Psychographic - Psychographic segmentation dives even deeper into the internal workings of your consumers by grouping them together based on psychological characteristics, including personality, habits, beliefs, and interests. Great for lifestyle brands that want to align themselves with consumers who live or aspire to live the lifestyle that the brand promotes.
We are a multi-market platform. My reason is that the meals and recipes we generate have to be pulled from sources otherwise the foods we suggest will be a chaotic slurry of ingredients. If I'm wrong about any of this please let me know!
So, the most important things are:
We are selling for a niche market.
We have a psychographic (AKA lifestyle based) customer model.
We are multi-platform.
And, as for diversified, we can explore options related to fitness and more health, to keep in touch with our customer model.

**Comment by Cade5480** [comment]
Credit to Aleksandra for compilating all this information! It looks good!

**Comment by BeepDroid** [comment]
This is awesome! I love how this looks! Amazing job!

**Comment by aaleksandraristic** [comment]
Thanks @Cade5480 for creating an Issue for this and uploading the files! 

**You all did awesome, and I am sure that we will continue working hard and complete our project very well!**

**Comment by Cade5480** [comment]
Thank you!! We can look into closing this issue soon! It looks good!

**Comment by bdshanks-28** [comment]
Aye-Aye!
