### ISSUE TITLE
MVP - Sprint (Discussion)

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#127]
MVP Setup
------------------------------------

Description: 
----------------------------

Developing an Android app and aiming to create an MVP (Minimum Viable Product) by the end of the month. Suggested roadmap and tasks are listed below in the section 'Steps to Reproduce'.

Steps to Reproduce: 
-------------------------------

1. Review Existing Framework - Assess the current state of the app framework and identify any areas that need improvement or expansion.
2. Implementation of logic
3. Prioritize and Refine Features: Implementation of at least one feature - Reevaluate the prioritization of features based on what's already implemented. Identify any missing critical features that need to be added.
4. User Interface Enhancements - Refine the existing user interface based on feedback or usability testing. Ensure a consistent and polished design throughout the app.
5. Core Functionality Completion - Finalize the implementation of core features that are in progress. Address any gaps in functionality.
6.  Bug Fixes and Quality Assurance - Conduct a comprehensive round of testing to identify and fix any bugs. Ensure the app meets quality standards.
7. Performance Optimization - Optimize the app's performance, addressing any bottlenecks or slow-loading components.
8. Decorating the app (design and colors)
9. Testing (alpha (closed), beta (open testing))

Expected vs. Actual Behavior: 
-------------------------------------------

**Week 1: Review Existing Framework**
-------------------------------------------- 

Evaluate the current app framework
Identify areas for improvement or expansion
Implementation of Logic

Develop and implement necessary logical components
Ensure seamless integration with the existing codebase

**Week 2: Prioritize and Refine Features**
---------------------------------------------------

Implement at least one prioritized feature
Reevaluate feature prioritization based on the implemented ones
Identify and document missing critical features
User Interface Enhancements
Finalize implementation of core features in progress

Review user interface based on feedback
Conduct usability testing
Implement refinements for a consistent and polished design

**Week 3: Core Functionality Completion and Testing**
-------------------------------------------------------------

Address any gaps in functionality based on feedback
Bug Fixes and Quality Assurance

Conduct comprehensive testing
Identify and fix bugs
Ensure the app meets quality standards

**Testing (Alpha - Closed)**
Conduct closed alpha testing
Gather feedback from a limited user group
Address issues identified during alpha testing

**Week 4: Performance Optimization and Testing**
-----------------------------------------------------------

Optimize app performance
Address bottlenecks or slow-loading components
Conduct performance testing
Decorating the App (Design and Colors)

Enhance the app's visual appeal
Implement design changes and color schemes

**Testing (Beta - Open)**
Launch open beta testing
Collect feedback from a broader user base
Address any critical issues reported during beta testing
Final Checks and Documentation

Perform final checks on the app

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

Operating System: Android
Firebase SDK Version: 23.0.0
Kotlin Version: 1.5.21
Android Studio Version: 4.2.1
Gradle Version: 7.0.2
SQLite3 3.45.1.

For Investigations/Research:
------------------------------------------

The objective is to organize and develop MVP by the end of March. Currently, we are working on implementing the logic and the next step is features development. 

Current Status: In progress
------------------------

**Comment by bdshanks-28** [comment]
I think as long as we have an mvp by this Friday, we should be on track. And if we aren't, then we really may have to gut what we have in terms of what we want to be able to do. Keep it in mind please.

**Comment by aaleksandraristic** [comment]
@bdshanks-28 I agree, we should speed up a little bit and try to get it done by this Friday.
