### ISSUE TITLE
ERROR - Edamam Meal Planner Code 401

### ISSUE THREAD

**Issue by IanTDuncan** [IanTDuncan/MealTime#129]
ERROR - Edamam Meal Planner Code 401
------------------------------------

Description: 
----------------------------

This issue is for a specific error I encountered while using the "try-out" function on the Edamam Meal Planner documentation. It is an undocumented error 401: {"message": "Missing or invalid credentials."}

Steps to Reproduce: 
-------------------------------

1. Make sure to authorize yourself using the app_id and app_key given by Edamam on the website, make sure it is the appropriate credentials
2. Once again, put the app_id into the appropriate textbox as well as your username
3. Execute the example code

Expected vs. Actual Behavior: 
-------------------------------------------

**Expected Behavior:** Return a code 200 which indicates that the request went through and it returns meals
**Actual Behavior:** Returns a code 401 which states that I have invalid credentials 

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

Operating System: Windows 11

### Investigation:
------------------------------------------

**Objective:** Investigate Error 401 and why I possibly have invalid credentials

**Findings:**
 This error is specific to /{app_id}/select which generates the meal plan based on provided materials.
 However /(app_id}/shopping-list which returns a shopping list returns results/hits and it uses the same credentials. 
 
 **Evidence:**
 
![image](https://github.com/IanTDuncan/MealTime/assets/143751333/6b23dd86-9603-4a72-8149-71326a4e3b17)

The FAQ on the website has nothing about this error within this context and the only thing I found online that relates to this is someone having the same error here: https://stackoverflow.com/questions/78055491/edamam-meal-planning-api-returning-401-error-with-valid-app-id

However, they also weren't able to find an answer either.

As of 3/4/2024 I sent Edamam an email detailing the problem.

_____

### Issue Resolution

As of 3/5/2024, I have still not received a response from Edamam so I am closing this issue

### Current Status: 
------------------------

### COMPLETED

**Comment by aaleksandraristic** [comment]
@IanTDuncan have you heard back from them? Any new information?

**Comment by IanTDuncan** [comment]
@aaleksandraristic No I think I'll close the issue and mark it as completed if it's okay with you.

**Comment by aaleksandraristic** [comment]
Yes, just put the mention in the formatted section above that you didn't receive any feedback from them.
