### ISSUE TITLE
Elevator Test Statement

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#13]
The “elevator test” is the ability to explain an idea—no matter how abstract—in about the time that it takes to
ride up or down a short elevator. The purpose is to describe the offering in simple terms that are free of hype.

**Comment by bdshanks-28** [comment]
We are making a simple app to track meals and calories of food for the user to try and help on their weight loss jounrey.

**Comment by BeepDroid** [comment]
We're developing an app for people interested in a healthier lifestyle, good food, and having all of that on an affordable budget.

**Comment by Cade5480** [comment]
We are creating an app called MealTime, this app is being developed for people are trying to find a successful way to track their eating lifestyle and see benefits through eating healthier.

**Comment by aaleksandraristic** [comment]
We are developing an app for both those who are interested in tracking their food consumption and those who are required to do so due to health difficulties. They have the ability to generate recipes, pick certain ingredients, make grocery lists, and keep checks on daily caloric intake. Our unique selling point is our visual user interface, which impacts the user's enjoyment by making things simpler and clearer to use.

**Comment by Cade5480** [comment]
I think this is looking good!

**Comment by IanTDuncan** [comment]
We are developing an app for people to track and plan meals as well as keep track of nutritional information such as calories.

**Comment by aaleksandraristic** [comment]
All answers are looking good so far, we are all on the same track! 

What do you think about these responses?

I think it should be longer than one sentence (30-45second are not that short while we're speaking haha)
 @BeepDroid @Cade5480 @bdshanks-28 @IanTDuncan

**Comment by IanTDuncan** [comment]
@aaleksandraristic Yeah I see now I'll work on editing my statement.

**Comment by Cade5480** [comment]
I would say we could look to close this issue, what do y'all think?

**Comment by bdshanks-28** [comment]
I think so too.

**Comment by Cade5480** [comment]
Sounds good, we can use Ians statement for our finalized statement. We will see what @aaleksandraristic and @BeepDroid think.

**Comment by BeepDroid** [comment]
I think that sounds good!

**Comment by Cade5480** [comment]
I have adjusted our Elevator Statement that was turned in on Moodle and will be closing this issue since it has been resolved.
