### ISSUE TITLE
Firebase Deletion - Backend Development

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#130]
### Description:
Since we are moving into SQLite, I am going to be going through our code and making sure all things firebase is deleted.

### Steps to Reproduce:
N/A

### Expected vs. Actual Behavior:
N/A

### Code snippets:
`package com.example.mealtime1

import android.os.Bundle
import androidx.activity.ComponentActivity
import com.google.firebase.FirebaseApp
import com.google.firebase.database.*

class GroceryListActivity2 : ComponentActivity() {

    private val groceryListRef: DatabaseReference by lazy {
        FirebaseDatabase.getInstance().getReference("groceryList")
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Initialize Firebase
//        FirebaseApp.initializeApp(this)

        // Create a new grocery list and push it to the database
        val newGroceryList = GroceryList(
            "uniqueListID",
            "uniqueUserID",
            "uniqueFoodID",
            System.currentTimeMillis(),
            "Groceries",
            200
        )
        groceryListRef.child(newGroceryList.GroceryListID).setValue(newGroceryList)

        // Retrieve a grocery list from the database
        groceryListRef.child("uniqueListID").addListenerForSingleValueEvent(object : ValueEventListener {
            override fun onDataChange(dataSnapshot: DataSnapshot) {
                if (dataSnapshot.exists()) {
                    val retrieveGroceryList = dataSnapshot.getValue(MealData::class.java)
                    // Grocery List exists
                } else {
                    // Grocery List does not exist
                }
            }

            override fun onCancelled(databaseError: DatabaseError) {
                // Handle error
            }
        })
    }
}`

### Environment Details:
IDE: Android Studio
SDK: 34.1.2

### Issue Resolution:
N/A

### Current Status: Completed

**Comment by aaleksandraristic** [comment]
@Cade5480 Sorry for this, but just to remind you that a due date for this issue is tomorrow. Please let me know if we need to expend it.

**Comment by aaleksandraristic** [comment]
@Cade5480 Same here, I am so sorry! Have you started working on it and what date should we specify as a due date for this issue?

**Comment by Cade5480** [comment]
Need to speak with Aleks and clarify with Aleks what all I can delete Firebase wise before I commit the deletions

**Comment by aaleksandraristic** [comment]
Sorry I just saw you comment, I haven’t received the notification! 

Yes, you can delete everything that uses Firebase, bc we are not using it for anything.

**Comment by Cade5480** [comment]
Deleted all firebase usages, closing issue

**Comment by aaleksandraristic** [comment]
Thank you!!
