### ISSUE TITLE
API - Spoonacular - API Investigation

### ISSUE THREAD

**Issue by IanTDuncan** [IanTDuncan/MealTime#132]
### API - Spoonacular API Investigation
______

### Description:

This is an investigation I've done into Spoonacular. The objective of this investigation is to identify which of the Spoonacular APIs are best suited for MealTime's many services. As such I will try and keep the various Spoonacular API services within their various categories.
______

### Initial Findings:

Based on the documentation [here](https://spoonacular.com/food-api/docs). Spoonacular has plenty of APIs, but the majority of ones we'll be using are from the Meal Planning Section along with a few from the Recipe section.

______

### Steps For Investigation:

1. Identify what services our app is using
2. Identify which of the services Spoonacular API offers match up to the ones we want
3. Select those APIs and investigate them more thoroughly

______

### Results of Investigation:

**Meal Planning**

- Get Meal Plan Week
- Get Meal Plan Day
- Add to Meal Plan
- Delete from Meal Plan
- Get Meal Plan Templates
- Add Meal Plan Templates
- Delete Meal Plan Templates
- Get Shopping List
- Add to Shopping List
- Delete from Shopping List
- Generate Shopping List
- Connect User

**Recipes**
- Get Recipe Information
- Price Breakdown by ID

_____

### Next Steps:

Get feedback and suggestions from teammates about which APIs to work on.

____

### Environment Details: 

Operating System: Windows 11
_____

### Current Status:

**COMPLETED**

**Comment by BeepDroid** [comment]
### Spoonacular API Investigation 
_____________________________
### Description 
____________________________
Responding to Ian's initial commit to this issue with an additional idea for one of the APIs, but the ones he's listed thus far I already completely agree with using. Further down in this post I'll also be listing the resources I've found that have to do with using and implementing Spoonacular API for easier access during our development. 

## Initial Findings
___________________________
@IanTDuncan I think another one we can add, time willing, would probably be "Get Similiar Recipes" from the document link you provided. Again, only if time allows, it can be something we leave last in the case we have to start shaving off features. 

As for our resources, this is what I have so far: 
[A walkthrough by Reintech](https://reintech.io/blog/building-recipe-app-android-spoonacular-api) -- This is a walkthrough on how to get started with the Recipe API using Postman as a resource,; Postman, which will be posted further down, is an alternative to the SDK if needed. 
[This is a video walkthrough for the same API using Retrofit](https://youtu.be/6-891CSz6v0?si=u_5lpLalpHfQxFqu) -- This is an implementation of the Random Recipe Spoonacular API through a multi-step video walkthrough of connection and implementation using Retrofit. 
[A Video on how to get started with Spoonacular](https://youtu.be/V20Mj4w-7K4?si=469SqqKD1wjsL_C6) -- This addresses things like your user key and how to do API calls. 
[Another full tutorial on how to implement the API](https://youtu.be/xxJN4GtBE9Q?si=jt-VinUctdPQH-wf) -- This pretty much takes us on the entire creation of an app from start to finish with the Spoonacular API; however, it isn't in English. I think we can still follow along the logic seeing it being typed out.

### Next Steps: 
_______________________
Begin connection ASAP while going through all our resources and documentation. 

### Current Status: 
_____________________
In progress

**Comment by IanTDuncan** [comment]
@BeepDroid Will definitely look into those tutorial
@aaleksandraristic Is it okay if I close this issue? I believe I have gotten all the suggestions possible

**Comment by aaleksandraristic** [comment]
@IanTDuncan Sorry for my late response, yes, go ahead and close the issue. Then for each of these implementations, you should create separate issues.
