### ISSUE TITLE
Addition of colors into resource folder

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#154]
Addition of colors into resource folder
------------------------------------

Description: 
----------------------------

Addition of colors using hex for the colors to use in decorating of UI.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

    <color name="gray_2">#21212121</color>
    <color name="blue_special">#25BAEB</color>
    <color name="green_special">#2FEB83</color>
    <color name="weird_blue">#004258</color>
    <color name="weird_pink">#C22B55</color>

Environment Details: 
------------------------------

Android Studio IDE
Kotlin

For Issue Resolution:
------------------------------

N/A

For Investigations/Research:
------------------------------------------

Speak with team about primary color range (4-6 to use).

Current Status: 
------------------------

In progress

**Comment by bdshanks-28** [comment]
@BeepDroid @aaleksandraristic @Cade5480 @IanTDuncan Let's think about our main color scheme here so I know what colors to import

**Comment by aaleksandraristic** [comment]
I don't know if we are going to stick with pastel colors. I am a fan of the dark background and dark mode for all of my apps. We can use some combination of deep blue or black and then all the options could be different colors. This is one of the examples that I like, but of course whatever most of us agree with. 

![image](https://github.com/IanTDuncan/MealTime/assets/140200824/213407f8-80b1-46da-8161-581cb18659a4)
![image](https://github.com/IanTDuncan/MealTime/assets/140200824/49545e7c-96d1-47f4-894e-fe18bde0f0e5)

**Comment by bdshanks-28** [comment]
Code snippets has been updated
