### ISSUE TITLE
Detailed feature description for Box

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#16]
Ideally we would have an app that a user can use on their mobile device to track their calories consumed throughout the day. How this would happen is the user would search up the food in a menu to pull the data of the specific food they are looking for. Once they find it, they 'add' it to what they have ate that day and all the nutritional info is given along with adding that amount of calories and macros to what they ate that day. As they add more foods to what they have ate for a given day, they will get a better breakdown of what all exactly they have ate (based off of macros like protein, sugar, carbs) and how many overall calories they have consumed in that day. By doing so, it will become easier to watch what the user eats and plan meals around a healthier lifestyle.

**Comment by Cade5480** [comment]
That sounds great Brandon, I like the description.

**Comment by bdshanks-28** [comment]
Sounds good enough to close?
