### ISSUE TITLE
App Demo 

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#163]
This will be where we can put pictures if need be, I will upload the splash screen here

**Comment by Cade5480** [comment]
https://github.com/IanTDuncan/MealTime/assets/143129097/59181a8f-6c00-461a-87d1-d9f468dd07cb

**Comment by IanTDuncan** [comment]
Example of a Meal Plan Being Generated
![image](https://github.com/IanTDuncan/MealTime/assets/143751333/89668c8b-e069-4190-b7a2-463295c7e511)

**Comment by aaleksandraristic** [comment]
Thank you @Cade5480 for creating the issue! Also splash screen looks great for now. We'll need to change some things but that's for later on. 
@IanTDuncan could you please explain what is this so he can know what's happening here?
@bdshanks-28 could some of you please take screenshots of all the pages that we have? 

@BeepDroid @Cade5480 @bdshanks-28 @IanTDuncan What do you think should we add something else besides screenshots of the app, splash screen and generate meal response?

**Comment by Cade5480** [comment]
Yes ma'am sounds good just let me know!

**Comment by aaleksandraristic** [comment]
We can discuss it on Saturday when we meet, take these days to rest, or if you have anything else to work on

> Yes ma'am sounds good just let me know!

**Comment by BeepDroid** [comment]
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/eadeafd7-5095-4af6-8f45-b93c27c22bd1)
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/8c8f2659-d4c7-4f1b-9cf7-e3d2e6454975)
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/ab7cd5f8-f81d-4533-9c33-d5b862a50e9c)
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/3e0129b8-abf7-4538-8f0a-607e756e4390)
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/35eeca5b-2802-4c96-87b6-5e981ad37a60)

**Comment by BeepDroid** [comment]
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/c593eaa2-9411-4c4e-9acb-67b1f7b813e4)
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/e4d7909f-1d85-462d-a004-e2b3ff1f7511)
