### ISSUE TITLE
March Sprint Retrospective

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#169]
March Sprint Retrospective
------------------------------------

Description: 
----------------------------

This issue is for the whole team to discuss potential problems that we had for the past month/sprint and make a retrospective of things that went well/bad and what should be improved for our next one.

- @BeepDroid @Cade5480 @bdshanks-28 @IanTDuncan 

Retrospective Summary:
------------------------------

**Went wrong:**

- [ ] Not being able (me) to properly connect and test out our app to the Firebase RealTime Database (online) -> Decided to switch to SQLite which is much easier to understand, implement, and test. 
- [ ] Too many errors occurred while working with API Edamam Meal Planner (Ian & Kerry) and it would take a lot of time to fix them -> We decided to switch to Spoonacular which is more used by others, and there are more tutorials available online. 
- [ ] [Addition of hyperlink for string resources](https://github.com/IanTDuncan/MealTime/issues/153#issue-2192185318) issue #153 - I guess there was a bad communication between Cade and Brandon so this issue wasn't completed s quick as we expected. 
- [ ] The problem with the Meal Generate button (Ian) @IanTDuncan could you please explain what is the problem here?
- [ ] Not following initially created issues, which is fine, but all those issues remained open -> We should communicate better about issues and tasks that we are creating at the beginning of the sprint so we don't get into a situation like this. 

**Went well:**

- [ ] UI design - Brandon was following our advice and changed everything that needed to be changed. I would say that this issue went very well even though there were a lot of changes. We were working on this during our team in-person meetings so changes and testings were done quickly. 
- [ ] Splash Screen - At the last moment we decided to get rid of the Login and Registration page, and implement a splash screen when the app starts loading -> Cade did an amazing job by working on this issue and implementing a splash screen fast. 
- [ ] API - Spoonacular - Ian and Kerry switched from Edamam Meal Planner to Spoonacular very quickly and they were able to complete a lot of work in such a short period of time. 
- [ ] Team communication - I like how we are communicating between each other and keep everyone posted on their issues and progress. 
- [ ] In-person meetings - I would say that these meetings are important and a huge improvement for our teamwork and team organization. 
- [ ] Members independence - All team members are independent by creating their own issues, adjusting due dates, and providing the information in well formatted GitHub issues. (Thank you)

**Goals for the upcoming month:**
- Add new features if it's possible
- Test the app on a mobile device
- Prepare for the presentation 
- Presentation Day (April 24th)

Keep this working speed and organization; team meetings will still remain for this month; get well prepared for the presentation

**Comment by aaleksandraristic** [comment]
@BeepDroid @bdshanks-28 @Cade5480 @IanTDuncan 
Hey guys, I just posted the retrospective overview above. Please, take a look and let me know if something needs to be changed or added! I might missed something so feel free to write it below.

**Comment by Cade5480** [comment]
There is nothing I can think of personally that would be missing, for the most part it looks good to me!
