### ISSUE TITLE
Design the Box - "The Sell"

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#17]
1. Easy way to count calories while being able to put together a grocery list simultaneously.
2. Provides opportunity to live a healthier lifestyle, user can keep track on if they have exceeded the average calorie limit, user will also receive notification on when limit has been reached.
3. Ability to choose a multitude of different food combinations to count calories or to put on a grocery list and to save that grocery list if it has been effective.

**Comment by bdshanks-28** [comment]
This is a good sell for points 1, 2 and 3. All big points I hope we can follow through on.

**Comment by BeepDroid** [comment]
Great selling points! Maybe sneak in the recipe generation mention. We've got a solid round up on this.

**Comment by IanTDuncan** [comment]
I like all the points, though we may have to narrow down or include some points depending on who we're "selling" too.

**Comment by aaleksandraristic** [comment]
I agree with all the selling points, good job!
