### ISSUE TITLE
Presentation 

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#172]
Presentation Format - Planning
------------------------------

Description:
-------------------------------

This issue is made to list all the required parts for the final presentation. For each part I will create a separate GitHub issue so we can easily keep track of changes. 

Here is the link to the presentation
-----------------------------------------

https://lsus-my.sharepoint.com/:p:/r/personal/b19001916_lsus_edu/Documents/CSC%20481%20Demo%20presentation.pptx?d=w453fa969e6f2416889ee3e2d67018367&csf=1&web=1&e=XzsYMn

The Presentation Format is shown below:
---------------------------------------------

Introduction:

Start with a brief introduction to your project, clearly stating the problem statement or opportunity you are addressing.

Team Introduction:

Introduce your team members and outline their roles in the project. This adds a personal touch and clarifies responsibilities.

Technologies Used:

Provide an overview or detailed explanation of the technologies implemented in your project, including the rationale behind their selection.
Mention any challenges encountered with these technologies and the solutions you devised.

Live Demo of the App:

A live demonstration of the app is required. Highlight the key features and how they address the problem or opportunity identified.
Prepare for potential technical issues by having backup materials ready, such as screenshots or a video demo.

Current & Future Plans:

Current Status: Describe the current development stage of your app and any immediate next steps.
Future Development: Discuss the future trajectory of your app, including upcoming features, market strategy, and potential obstacles.

Presentation Length:

Your presentation should not exceed 30 minutes, allowing time for a comprehensive overview and a live demo.

Q&A Session:

A Q&A session will follow your presentation. Allocate time within your 30-minute slot for this interaction, preparing to answer questions concisely.

Visual Aids:

Use visual aids like slides or diagrams to support your presentation. While there is no strict limit on the number of slides, ensure they are clear and directly relevant to your points.

Technical Requirements:

Ensure that you have tested and are familiar with any software or hardware you will use during the presentation. This includes ensuring a stable internet connection for the live demo.

Also, there is a certain evaluation criteria:
----------------------------------------------

Your presentation will be assessed based on clarity, depth, technical understanding, and the effectiveness of the live demo. Additionally, your ability to answer questions and articulate your project’s current status and future direction will be considered.

Issue Status: In Progress
---------------------------------

**Comment by aaleksandraristic** [comment]
@bdshanks-28 I remember you saying that MS PowerPoint has nice presentation designs, should we use that or something else for creating the presentation? Is it possible to somehow share the pptx so everybody can have the access at the same time?

**Comment by bdshanks-28** [comment]
Yeah there is a way, I can try and get it set up during the meeting on our school emails using the Microsoft features our school accounts use.
________________________________

**Comment by aaleksandraristic** [comment]
@bdshanks-28 Could you please share the link of the presentation in this issue?

**Comment by aaleksandraristic** [comment]
@bdshanks-28 @BeepDroid @Cade5480 @IanTDuncan 

Guys, just a reminder that we are presenting tomorrow, would you be okay if we present like the following:
1. Start - me 
2. Contents - me
3. Intro - me
4. Team Members - me 
5. Tools Used (Technologies) - @Cade5480 
6. Live Demo - @BeepDroid & @IanTDuncan 
7. Current & Future Plans - @bdshanks-28 

Please let me know what you think. Y'all should have been already assigned to these issues.

**Comment by Cade5480** [comment]
Sounds good, I will finish up my slide today!

**Comment by aaleksandraristic** [comment]
Sounds good, thank you @Cade5480!!

**Comment by bdshanks-28** [comment]
Notes:

Clear speaking
Introduce ourselves as grad or undergrad, major and concentration
check grammer
database needs to be referenced being done by Aleks
Meet the team
 -split between everyone
 -present tense
Tools
 -Android studio IDE - shorten
 -SQLite - shorten
 -Java + Kotlin - mention it as a programming language, shorten
mention firebase and edaman offhand when referring to databse and api
mention github
 - use CI/CD pipeline
 - debugging software - look at century.io
 - analytics
Data Analytics
 - fix UI/UX
 - Merging
 - Workflow

**Comment by bdshanks-28** [comment]
Storyboard ig for some reason
