### ISSUE TITLE
Presentation - Team Introduction

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#174]
Presentation Team Introduction
--------------------------

Description
--------------------

Introduce team members and outline their roles in the project. This adds a personal touch and clarifies responsibilities.
Also, it would look professional if we have our pictures and then little text of what we have done.

Assigned to: @bdshanks-28 & @aaleksandraristic 
---------------------------------------

Status: In Progress
--------------------------------------

**Comment by aaleksandraristic** [comment]
![1640198416462](https://github.com/IanTDuncan/MealTime/assets/140200824/6b3a4ee3-d594-431c-b990-82ad9d2d34fa)

**Comment by bdshanks-28** [comment]
Grabbed mine and Cade's off of linkedin

**Comment by bdshanks-28** [comment]
Everyone's photos is in the slides. 

@aaleksandraristic we cannot fit our degree, year and concentration in there it becomes too crowded. I already tried.

**Comment by bdshanks-28** [comment]
Closing this
