### ISSUE TITLE
Presentation - Technologies Used

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#175]
Presentation - Technologies Used
------------------------

Description
---------------------

Provide an overview or detailed explanation of the technologies implemented in your project, including the rationale behind their selection.

Mention any challenges encountered with these technologies and the solutions you devised.

Assigned to: @Cade5480 
-----------------------------------

Would you be okay doing this part for the presentation? I remember you doing technologies part during the last semester so I thought maybe you can do it again, or you would prefer something else? 

Status: In Progress
-------------------------------------------

**Comment by aaleksandraristic** [comment]
@Cade5480 Please let us know if you need any help with this part!

**Comment by Cade5480** [comment]
All done!

**Comment by bdshanks-28** [comment]
Added firebase and google analytics. Also cut down on words for each thing.
