### ISSUE TITLE
Presentation - Current & Future Plans

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#177]
Presentation - Current & Future Plans
-----------------------------------------

Description
------------------------

Current Status: Describe the current development stage of your app and any immediate next steps.
Future Development: Discuss the future trajectory of your app, including upcoming features, market strategy, and potential obstacles.

Assigned to: @bdshanks-28 
------------------------

Status: In Progress
------------------------------------

**Comment by bdshanks-28** [comment]
Review Aleks and see if anything needs to added or removed and we can look at closing this.

**Comment by aaleksandraristic** [comment]
@bdshanks-28 Looks good, do you have the speech for this ready? You can go ahead and close this issue

**Comment by bdshanks-28** [comment]
I have it generally ready yeah.
________________________________
