### ISSUE TITLE
App Icon Design

### ISSUE THREAD

**Issue by BeepDroid** [IanTDuncan/MealTime#18]
![thumbnail_MealTime Application Icon](https://github.com/IanTDuncan/MealTime/assets/71675347/2b9a436c-64cd-48d6-b719-c2247b984f96)

This is our alpha design for the app, worked on by myself and Ian. The mockup of the meal page I did previously will be uploaded to this issue later. Feedback, suggestions, all welcome and anticipated.

**Comment by IanTDuncan** [comment]
We already have some improvements planned such as adding more details, shading, and smoothing out some rougher parts.

**Comment by aaleksandraristic** [comment]
![MealTime Title Font](https://github.com/IanTDuncan/MealTime/assets/140200824/37066f0b-5266-405c-92a0-dcdc60a3e2d4)

**Comment by Cade5480** [comment]
Its looking good!

**Comment by BeepDroid** [comment]
![2898C2EA-E2C3-423E-9E52-477193585903](https://github.com/IanTDuncan/MealTime/assets/71675347/bc15cb2c-545a-4bd5-9c39-9b2cb0839a11)
Throwing up the drawn out page designs for loose reference
