### ISSUE TITLE
Presentation - Work Pipeline

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#183]
Work Pipeline slide
------------------------------------

Description: 
----------------------------

Describe our work pipeline (Github) with the help of our CI/CD pipeline from last semester.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/a

Environment Details: 
------------------------------

N/A

For Issue Resolution:
------------------------------

Explain our work pipeline then show our diagram. Should have it from last semester.

For Investigations/Research:
------------------------------------------

N/A

Current Status: 
------------------------

In progress

**Comment by bdshanks-28** [comment]
[Uploading Agile.development (1).pdf…]()

**Comment by bdshanks-28** [comment]
[Work Pipeline for Mealtime.pdf](https://github.com/IanTDuncan/MealTime/files/14953584/Work.Pipeline.for.Mealtime.pdf)

**Comment by bdshanks-28** [comment]
Review slide

**Comment by aaleksandraristic** [comment]
Should we change the name to CI/CD Pipeline? 

Also, should Kerry present it since it was her work last semester or would you be okay with presenting it?

**Comment by bdshanks-28** [comment]
I can present it since I had to remake it a little from last semester. And yeah but I have to remember what CI/CD stands for.
________________________________
