### ISSUE TITLE
Presentation - Analytics slides

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#184]
Analytics Slides
------------------------------------

Description: 
----------------------------

Describe how our analytics function for the app and how we track them through google analytics applied through firebase.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

N/A

For Issue Resolution:
------------------------------

N/A for now

For Investigations/Research:
------------------------------------------

Research firebase and google analytics. These are further documented in issue #181.

Current Status: 
------------------------

In progress

**Comment by aaleksandraristic** [comment]
@bdshanks-28 do you need any help with this issue? You know that I don't like firebase, but I like analytics ahaha

**Comment by bdshanks-28** [comment]
Check over the slide, I think I hit everything that needed to be said
________________________________
