### ISSUE TITLE
Presentation - Describe our market audience

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#188]
Describe our market audience - Market Visbility
------------------------------------

Description: 
----------------------------

Describe the market visibility to the investors.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

N/A

For Issue Resolution:
------------------------------

Describe our market audience. Should fall back on previous presentations.

For Investigations/Research:
------------------------------------------

N/A

Current Status: 
------------------------

In progress

**Comment by aaleksandraristic** [comment]
@bdshanks-28 I'll go ahead and check what we have wrote last semester. Will upload everything here
