### ISSUE TITLE
3 Questions per group

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#189]
3 Questions for each group's project
------------------------------------

Description: 
----------------------------

Make 3 questions for each group's project for their Q&A.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

N/A.

For Issue Resolution:
------------------------------

N/A

For Investigations/Research:
------------------------------------------

N/A

Current Status: 
------------------------

In progress

**Comment by bdshanks-28** [comment]
Just 1 question for each group from everyone and that will give us a selection of 5 to pick and choose for each group.

**Comment by bdshanks-28** [comment]
Optiliv: How will you connect real estate agents or firms into your website? Will you allow for sale by owner?
IRB: Since it is a web app, will it only work on a closed system like Morris & Dickson presumably have? If so, would any updates require someone to go on site to update code?
Aquatic Rig: Will this tool be for dedicated researchers or will it be open for the public to do their own research with?

**Comment by IanTDuncan** [comment]
**Optiliv:** One issue we encountered early on was that grocery chains don't share their food prices due to competition reasons. Did Optiliv encounter similar issues?
**IRB:** Are there any plans to optimize loading times for the product, or is that unfeasible? 
**Aquatic Rig:** Is there a reasoning why you chose those specific visualization or are they the most common?

**Comment by BeepDroid** [comment]
**Optiliv:**  Will you allow for public estate/apartment reviews by current/former residents? If so, will there be any guidelines to these reviews to ensure no malicious action is taken?
**IRB:** What was the biggest hurdle you faced while implementing the system for your product?
**Aquatic Rig:** Do you think adding area specific mapping, such as over particular coral reefs or popularly monitored sea spots, would be beneficial?
