### ISSUE TITLE
Design the Box - Operating Requirements

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#19]

**Comment by IanTDuncan** [comment]
To use this app, you will need an Android Operating System with access to google play store to download and run our app.

**Comment by Cade5480** [comment]
Looks good, super straight forward, I would say it looks good!

**Comment by bdshanks-28** [comment]
Sounds good for now!

**Comment by Cade5480** [comment]
We can go ahead and close this issue!
