### ISSUE TITLE
April Retrospective

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#197]
April Sprint Retrospective
------------------------------------

Description: 
----------------------------

This issue is for the whole team to discuss potential problems that we had for the past month/sprint and make a retrospective of things that went well/bad and what should be improved

- @BeepDroid @Cade5480 @bdshanks-28 @IanTDuncan 

Retrospective Summary:
------------------------------

**Went wrong:**

- [ ] UI Design Task Assignment - Brandon was the first one who was working on the project but it didn't work that well. Later on, Kerrigan stepped in and updated the app's design much better than it was before. She created additional pop-ups and upgraded the images' view, and nutrition label, and arranged buttons around. 
Solution: Make a better organization between team members, and choose the ones who have more experience and love doing design. 

- [ ] [BUG - MealResult.kt - Error Loading Image](https://github.com/IanTDuncan/MealTime/issues/185) # 185
Essentially some of the meals generated would not have an image available. With no image available the MealResults.kt page crashed.
Solution: This was fixed by whenever encountering a null value for the image a placeholder image would be inserted in its stead.
- [ ] [API - Spoonacular RecipeSearch Integration](https://github.com/IanTDuncan/MealTime/issues/165) # 165
RecipeSearch was supposed to be able to return nutrition information, but this wasn't working despite using it with/without retrofit. 
Solution: This was amended by using a separate API, which is the nutrition label image API.
- [ ] Google Play Store Setup - The process of verifying and setting up the app on Google Play Store was taking much longer time than expected (2 weeks for verification + 2 days per app version) 
Solution: Research more about time consumption before it's too late. 

**Went well:**

- [ ] Some of the issues from the past month were moved to this one and shortly got closed. 
Solution: Solving issues much faster; keeping track of related ones; if there is a problem we don't spend as much time as we did before, so we just research the other way to do it.
- [ ]  Final Presentation - Went pretty well, and much better than the practice ones. 
Solution: Good organization; speech practice; notes on the side; slides division between members who feel confident of presenting 

**Goals for the upcoming month:**
If we decide to continue working on this project and actually make it a reality and publish it, we will keep all the comments and feedback from our teammates and audience in mind and try to implement as much as possible. We would improve our app’s functionalities and add more features.

**Comment by IanTDuncan** [comment]
BUG - MealResult.kt - Error Loading Image #185 

> Essentially some of the meals generated would not have an image available. With no image available the MealResults.kt page crashed. This was fixed by whenever encountering a null value for the image a placeholder image would be inserted in it's stead.

API - Spoonacular RecipeSearch Integration #165 

> RecipeSearch was supposed to be able to return nutrition information, but this wasn't working despite using it with/without retrofit. This was amended by using a seperate API, which is the nutrition label image api.

@aaleksandraristic I hope this clears some things up.

**Comment by aaleksandraristic** [comment]
@IanTDuncan Yup, it does! Thank you!!
