### ISSUE TITLE
Key Activities

### ISSUE THREAD

**Issue by IanTDuncan** [IanTDuncan/MealTime#2]
What Key Activities do our Value Propositions require?
Our Distribution Channels? 
Customer Relationships?
Revenue streams?

**Comment by IanTDuncan** [comment]
Our distribution channel(s) will be mobile platforms like IPhone and Android.

**Comment by IanTDuncan** [comment]
Revenue Streams:

 We start off with two option an initially paid app or an initially free app. If the app is paid, we'll have a steady stream of revenue as long as customers keep on buying the app. A free app, on the other hand, has can be supported by in-app ads and users can additionally pay to remove ads. Another option for the free app, is to lock features behind a subscription, therefore encouraging users to pay using the subscription. The last and least moral option is selling user's data, but I have obvious problems with this one.

**Comment by IanTDuncan** [comment]
The relationship we want between us and our customers is based on self-service and automated service. Since our app is mainly used by the customer with little to no input from us, it will be primarily automated to generate meals. We will also have a small community gathering around our app as users will be able to submit homemade meals/recipes. With these many relationships, we hope to foster a long-term relationship for continued use of our app.

**Comment by Cade5480** [comment]
For the distribution channel we should probably lean more towards android, I have "partners" who have experience with publishing apps on the play store.

**Comment by bdshanks-28** [comment]
Android also is cheaper to initially put up an app as well. Good idea.

**Comment by IanTDuncan** [comment]
Key Activities for Value Propositions: 

Our key activities will be delivering an in-app calorie tracker, a "grocery list" of foods and ingredients, and a meal generator. It will also be import to keep all these features up to date as these will be our selling point for the app. By making all of these features work smoothly individually and with each other, we'll be able to foster a good relationship with our customers.

**Comment by aaleksandraristic** [comment]
I like your answers to these questions, and I fully agree with all of the above!

**Comment by BeepDroid** [comment]
Android sounds good for getting out foot in the door!

**Comment by bdshanks-28** [comment]
Maybe a meal generator might be a little bad. Say something says... salad with a side salad. Plus we would have to break down meals based on every part of a meal while trying to make it even.

**Comment by IanTDuncan** [comment]
### Key Activities Closing Comment


**Key Activities our Value Propositions require**

Key activities are the key things our app do to deliver value propositions to the customer. These will be noted below.

1. An In-app calorie tracker
2. A "grocery list" of foods and ingredients 
3. A meal planner

By keeping all these features up to date and working with each other our customers will be satisfied and a long-term relationship will slowly grow.

**Distribution Channels**

- MealTime will be distributed via the internet through one of the app stores 
- The app store we will be focused on will be Android due to cost-saving and experience

**Revenue Streams**

- Our revenue steam will be a free app with ads 
- Users will be able to get rid of ads by paying a small monthly subscription

**Customer Relationship**

- The relationships we will have between us and our customers will be based on self-service and automated service
- Since our app is mainly used by the customer with little to no input from us, it will be primarily automated to plan meals

**Comment by aaleksandraristic** [comment]
This looks great! Good job Ian!
