### ISSUE TITLE
Agile Product Ownership

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#23]
![image](https://github.com/IanTDuncan/MealTime/assets/140200824/d98974d0-0e10-4fa6-8f3d-f0aff83bf126)

**Comment by Cade5480** [comment]
I do not think this requires anything of us, it is just for us to watch and be mindful of when creating this project!

**Comment by aaleksandraristic** [comment]
Yeah, I think so, but let's keep it for now, we can always rename it

**Comment by bdshanks-28** [comment]
If anything, unlike irb and aquatic rig, we can probably claim full ownership of the product in idea. Right?

**Comment by aaleksandraristic** [comment]
Agile Product Ownership
	- why are we building an app?
	- what problem is going to be solved and for who?
	- Stakeholders -> the people who are going to use and support or in any way be affected by the system being developed
	- develop the most important features first according to the capacity of the dev team 
	- when one feature is done the new one comes in (sequencing - what we build now and what later)
	- all the features requests - YES(dev team) or NO(trash)
	- some features are very expensive (time) - VALUE AND SIZE!!!

"Backlog Grooming" = The VALUE of the features and the SIZE -> Talk to stakeholders to find out what they value and continuously talk to the team to find out what they think is big or small in terms of implementation effort (COMMUNICATION!).

Trade-offs decisions:
- different types of value
business risk -> Are we building the right thing?
social risk -> Can these people build it
technical risk -> will it work on the platform that we want to run it on, will it scale
cost and schedule risk -> Can we finish the product in a reasonable amount of time for a reasonable amount of money

VALUE($) = KNOWLEDGE VALUE(?) + CUSTOMER VALUE(!)

What should we build next? - short-term/long-term thinking - BALANCE!!!
			   - build the right thing or build the thing tight or build it fast?

Product FORECASTING (line graphs)

**Comment by aaleksandraristic** [comment]
These are the main points from the video, as well as the graph above. 
If you want you can take a look at the video but you do not have to. 
I would recommend that we are all the owners of the product and members of the development team (since all of us are going to work on it) and then our STAKEHOLDER could be Professor Dr. Shardar. I think that would make this process complete, so we can communicate between us about all the features that we want to develop as well as the features that our stakeholder wants. 

What do you think about that? 
@BeepDroid @Cade5480 @bdshanks-28 @IanTDuncan

**Comment by Cade5480** [comment]
I think you explained it clearly, there is not a single thing i disagree with or can add to it. You actually did a really good job lol. Good job Aleks!

**Comment by bdshanks-28** [comment]
I agree with Kerry, everything here was covered really well and I can't disagree with it.
