### ISSUE TITLE
MealTime Improvements

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#24]
- given feedback from professor and other students according to our presentation on Tuesday (09/26)

**Comment by aaleksandraristic** [comment]
- App Icon Redesign
- Expand availability
- Bringing the user back
- Ways to profit
- Add more feedback as you see fit.

Decide how much function is internal and how much will need to be online content to be accessed.

**Comment by bdshanks-28** [comment]
Decide how much function is internal and how much will need to be online content to be accessed.

**Comment by aaleksandraristic** [comment]
**Comments from other students:**
--------------------------------------------------------------------------------------------------
Positioning statement is clear and informative.
Elevator test statement was nice but not in sales pitch format, tell why your app is better than other apps on the market.
Business Model Canvas is very clean and nicely explained, Great job!
Physical box is cool, I like the logo and the test UI a lot.
Box presentation was good and I liked that multiple people presented it. The icon matching real time is an awesome feature. I know our professor mentioned the reason behind using a burger, I like it but if y'all need more ideas maybe a waffle with the hands made of syrup, or something more health could be a pile of white rice with some sort of veggie or chicken as the hands and numbers? Just some ideas if y'all steel away from the burger. I wish the slides for the box presentation had the same formatting and pictures as the physical box. For the internet issue for shopping in a store, maybe the grocery list could be saved internally so that if you launch the app with no internet service it will go strait to the grocery list and only show that page until reconnected to the internet.
Closing was good, great job guys! I look forward to seeing the app be developed, I'm sold and will be downloading it for sure!
--------------------------------------------------------------------------------------------------
Positioning statement well written; The BCM looks very nice (Summarization of their detailed issues flows nicely with each other issues) I think that their envisioning presentation was good. Maybe for the logo design, if they wanted to change (not saying anything is bad with it), they could try having a person with their mouth open putting some sort of food in their mouth with a number on it to represent the calorie intake.
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------

**Comment by Cade5480** [comment]
Work on our negativity levels

**Comment by Cade5480** [comment]
One other improvement we are going to make is switching from swift to android studio. This just makes much more sense for the development to our android specific app.
