### ISSUE TITLE
Resource Learning

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#26]
This issue is going to be for where we can put our thoughts down when it comes to learning about the resources provided such as engagement and retention in apps, app adoption, A/B testing, and lastly material design!

**Comment by aaleksandraristic** [comment]
@Cade5480 Since we have all these issues separated, do we need this issue as well?

**Comment by Cade5480** [comment]
You're actually right, I don't think this issue is necessary, next person that sees this can confirm and close it.

**Comment by bdshanks-28** [comment]
Yeah I don't think this is really needed.

**Comment by aaleksandraristic** [comment]
Okay, sounds good!
