### ISSUE TITLE
App Adoption

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#28]
How the market like your app?
How to reach the market?

Link from the Moodle, but we can research on our own as well: 
https://cdn2.hubspot.net/hubfs/506011/Assets/Playbooks/App%20Adoption%20Playbook.pdf

**Comment by bdshanks-28** [comment]
This functions mostly with the channels I spoke of. We need a social media presence and start spreading to the market through word of mouth. That's the only way right now to even approach the market.

**Comment by aaleksandraristic** [comment]
What attributes should we use to evaluate a potential marketing channel?
--------------------------------------------------------------------------------------
![image](https://github.com/IanTDuncan/MealTime/assets/140200824/1fd94c49-9ce5-4df4-bfc6-d3f550af3a74)

**Comment by aaleksandraristic** [comment]
The most powerful channels for mobile app discovery? 
---------------------------------------------------------------

![image](https://github.com/IanTDuncan/MealTime/assets/140200824/b40db8d0-e457-4f9f-8c0c-9864204602c2)

**Comment by bdshanks-28** [comment]
1: Channels - as discussed, social media presence would be the best option for us at the moment to get news of our product out there. But judging by the graph, maybe letting it get pinged in the app store under certain search terms is good.
2. Some simple equations to measure app adoption success: Conversion rate = (conversions / total visitors) x 100,, Measure customers using a certain feature ( we will need data trackers then), usage frequency = number of users who access a product within a time frame / total number of users
3. Features would be the thing to rely on for retention as well as notifications
4. tied into 3

**Comment by BeepDroid** [comment]
Amazing charts! Everything is clearly illustrated and easy to follow. I am surprised at the amount of app discovery through the app store itself. Perhaps there's a way to get a spotlight on there?

**Comment by Cade5480** [comment]
This all looks really good! The graph and charts displays the information clear and concise.
