### ISSUE TITLE
GDPR & CCPA

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#29]
When is consent required?

1. **GDPR** = **General Data Protection Regulation (Europe)**
	-> Requires Consent
	a) In most cases
	- you need a legal basis before you can collect personal information from individuals online or offline (legal basis - get consent -> You are asking the individual for the right to go ahead and collect personal information from them in certain ways)
	-> Nowadays - cookies pop up on websites (you have to agree to allow cookies to collect information from you)

2. **CCPA** = **California Consumer Privacy Act (in the US)** (light version of GDPR)
	- no requirement of consent
	- Specific areas: health records, financial records, collection of information for minors under 13

2 different areas of consent requirements: 
		   1) you need consent - If you're collecting info from children 13-16 yo, you need consent from them, but if you're collecting info from kids under 13 - ask a parent
		   2) you don't need it

3. Certain types of cookies or tracking software - RESEARCH what would be the best for our app

4. Third-party tracking cookies - Google Analytics, not selling data - Make sure how this works

- notify the user, why you're using their info
- sharing data?

**Comment by IanTDuncan** [comment]
### **Tracking Software**

- Depending on our where we distribute our app we'll have basic tracking software, however we'll need more advanced software to get more useful data
- That data includes which features of our app are the most popular, where out users are clicking, where our customers are leaving
- I have identified **three** potential app tracking software that we can use with MealTime

1. **[UXCam](https://uxcam.com/)**

     - Provides a heat-map (i.e. which aspects of the app get the most attention)
     - See session replays of users using the app
     - User journey analysis
     - Qualitative android app analysis

2. **[Firebase](https://firebase.google.com/)**

    - Advanced crash reporting tool
    - Easy setup for Backend as a Service (BaaS) without having to maintain your own servers
    - Optimized for real-time apps
    - The free plan is small compared to other tracking software

3. **[Flurry](https://www.flurry.com/)**

    - Free
    - Allows monetization and promotion of apps through ads
    - Can compare your app's metrics with other apps of the same type
    - Not as much depth of analysis

**Comment by aaleksandraristic** [comment]
I like the UXCam so we can get a more detailed analysis and maps. 
- Flurry sounds good with these options for monetization and promotion, but does not give us much analysis. 

Are we able to combine them together, or we have to choose one?

**Comment by IanTDuncan** [comment]
@aaleksandraristic I imagine we can combine them together, one of the articles I read talked about using Firebase and UXCam together. The biggest problem I see with using two is that we would would have to integrate both into our app, which could slow down our and/or cause other problems.

**Comment by IanTDuncan** [comment]
### Consent and Tracking Software Preference 

**1. Consent**
We should ask the user to verify that they are 13 years of age before using the app, this way we can abide by both GDPR 
and CCPA regulations 

**2. Tracking Software Preference**
I now firmly believe that Firebase is best for MealTime. After developing a small program in Android Studio, I discovered that it has baked-in compatibility with Firebase which would increase the ease of use for us as developers.

Not much, in this comment due to this issue being nearly closed.

**Comment by aaleksandraristic** [comment]
Awesome findings! Thank you for testing it out.

**Comment by Cade5480** [comment]
This all looks great Ian! Good job!

**Comment by BeepDroid** [comment]
This all seems solid to me, awesome research compilation
