### ISSUE TITLE
Customer Relationships

### ISSUE THREAD

**Issue by BeepDroid** [IanTDuncan/MealTime#3]
What type of relationship does each of our
Customer Segments expect us to establish
and maintain with them?
Which ones have we established?
How are they integrated with the rest of our
business model?
How costly are they?

**Comment by BeepDroid** [comment]
My domain

**Comment by Cade5480** [comment]
Looks great so far!

**Comment by BeepDroid** [comment]
As I'm narrowing down the customer segment model (market and initial segment model determined for right now), I'm starting to think we're looking at a **self-service** type of relationship. IKEA is a fantastic example of this; they give you the parts, and you build it yourself. We're providing our customers with the ingredients, instructions, and health-related information, and it's up to them to prepare the actual food and stick to the generated plan. 

Any other thoughts on this? The other types of relationship models are dedicated personal assistance, personal assistance, automated services, communities, and co-creation for reference.

**Comment by BeepDroid** [comment]
Thus far, to my knowledge, we have **not** developed any current/on-going relationships with any customer base. 

Also, side-note, depending on if we decide on subscription based or one-time payments for our revenue, it will between **long-term** (subscription based) and **transactional** (one-time payment) as added to the expected relationships with customers.

**Comment by aaleksandraristic** [comment]
> As I'm narrowing down the customer segment model (market and initial segment model determined for right now), I'm starting to think we're looking at a **self-service** type of relationship. IKEA is a fantastic example of this; they give you the parts, and you build it yourself. We're providing our customers with the ingredients, instructions, and health-related information, and it's up to them to prepare the actual food and stick to the generated plan.
> 
> Any other thoughts on this? The other types of relationship models are dedicated personal assistance, personal assistance, automated services, communities, and co-creation for reference.

I like the comparison with IKEA, good explanation. 

I also agree with payments for our revenue. 
We can do a little research on what other similar apps are charging users for (like what features) and see how the market is taking it. Since our initial idea was to have a free app, maybe we can keep that option as well, but the question is where the money is gonna come from. Do we get any money from the app store when the app is downloaded by the user? (am not sure how detailed plan should be, and should we think about it)

**Comment by IanTDuncan** [comment]
Good job so far! I think you've definitely identified our primary customer relationship. I am curious about any potential future customer relationships that you may think will develop.

**Comment by BeepDroid** [comment]
Regarding how we will be integrating our customer base into our business model, as this is a self-service relationship, we will inegrate them by providing them with the means to store the data they receive. For example, should we decide to do a login function, the user can store their data, bookmarked meals, etc quite easily, making their lifestyle all that more attainable and accessible. Our main goal here is the retention of customers, not just aquisition, something we achieve with the services we offer. 

Customer retention is ensuring we are giving them _enough_ , with easy access, to not only keep them using the service, but to prompt the idea of them paying for it/subscribing to a monthly charge. 

As for cost, it depends on how many users we have to store. Should we amass a good amount of them, cost will depend on how many are online at one time and actively using the service. We may be looking at $84 yearly -- this is based off a hosting service I use for a website I host. The more users and activty we expect, the more expensive. But just for starting out, we're likely just looking at 60-80 a year.

**Comment by aaleksandraristic** [comment]
This looks perfect!! We can close this issue. I added it to the Business Canvas Model.
