### ISSUE TITLE
Development Tools

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#33]
List all the development tools that you will be using and what their role is. Also, note that if they are cloud based state where they are hosted. Example: Git hosted on Bitbucket will be used for source control.

**Comment by Cade5480** [comment]
Microsoft SQL Server:
Role: Microsoft SQL Server serves as a robust relational database management system (RDBMS), managing the storage, retrieval, and manipulation of structured data.
Hosting: Microsoft SQL Server can be hosted on on-premises servers or on cloud platforms like Microsoft Azure.

Slack:
Role: Slack plays a crucial role as a cloud-based team collaboration platform, providing channels for real-time communication, file sharing, and third-party application integrations.
Hosting: Slack is hosted on its own cloud infrastructure.

Swift:
Role: Swift serves as a powerful programming language developed by Apple for building our Android application with a focus on performance and safety.
Hosting: Swift is not hosted; it is used to develop applications that are hosted on Apple and Android devices.

Git (Hosted on GitHub):

Role: Version control system for tracking changes in source code.
Hosting: GitHub, a cloud-based platform for Git repositories.

**Comment by Cade5480** [comment]
Will add more if needed

**Comment by aaleksandraristic** [comment]
Looks good Cade, I think there is nothing else to add so far.

**Comment by BeepDroid** [comment]
Really clear and solid line-up of the tools we're using thus far, great job!

**Comment by Cade5480** [comment]
Sounds good, will be prepared to turn it in on moodle when the time comes

**Comment by bdshanks-28** [comment]
Should we add moodle since everything that goes to Slack/Github also goes there for submission?

**Comment by Cade5480** [comment]
I do not think so because if we took moodle out of the lineup it would not affect us in developing the app since it does not contribute to the app itself.

**Comment by Cade5480** [comment]
Android Studio:

Role: Android Studio is an integrated development environment (IDE) specifically designed for Android app development. It provides tools and features for designing, coding, testing, and debugging Android applications.
Hosting: Android Studio is a desktop application that is locally installed on developers' machines. It is not hosted in the cloud; instead, developers download and install it on their local systems to create and manage Android projects.
