### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#34]
Git = control system 
 - how to use Git to accomplish work in a consistent and productive manner

 When working with a team on a Git-managed project, it’s important to make sure the team is all in agreement on how the flow of changes will be applied. To ensure the team is on the same page, an agreed-upon Git workflow should be developed or selected. 
 
 Functionality - a repository for the code; team members will have access to the same code. Different methods and classes -> merge the information together (BRANCHING)

	-> issue number associated with the specific part of coding
	-> main branch - check out the issue/branch # 
	-> branch # = issue # 
	-> merging with the main branch (administrative)
	-> QA - checks the code
	-> start working on this...(structure)

**Comment by aaleksandraristic** [comment]
Here are some video tutorials and examples that could help: 

Git Tutorial: https://www.youtube.com/watch?v=Uszj_k0DGsg&ab_channel=freeCodeCamp.org

Git Branching | Git Tutorial | Git Commands: https://www.youtube.com/watch?v=vwik-o0wD5A&ab_channel=edureka%21

Shortcuts: https://www.youtube.com/watch?v=ecK3EnyGD8o&ab_channel=Fireship

**Comment by bdshanks-28** [comment]
Thanks for the extra tutorials posted for us to use!
