### ISSUE TITLE
Story Board Updated

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#35]
- Mockup of the application (Can use tools like Balsamiq)

http://www.betterprojects.net/2009/09/storyboarding-as-requirements-tool.html

**Comment by BeepDroid** [comment]
[Storyboard_MealTime.zip](https://github.com/IanTDuncan/MealTime/files/12851799/Storyboard_MealTime.zip)
Here is the zipfile for the updated story board! The following is a screenshot for easier access, but the best way to view it is through the zip.

**Comment by BeepDroid** [comment]
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/5b8144b3-cb8b-42ce-abcf-26be63e716bf)

**Comment by aaleksandraristic** [comment]
I love the way you did it, looks great!  Good job Kerry!

**Comment by Cade5480** [comment]
Oh wow did not expect to open this issue and see those mock ups. These look wonderful! Good job!!

**Comment by bdshanks-28** [comment]
Those look good so far, let's see what he has to say now.

**Comment by aaleksandraristic** [comment]
> [Storyboard_MealTime.zip](https://github.com/IanTDuncan/MealTime/files/12851799/Storyboard_MealTime.zip) Here is the zipfile for the updated story board! The following is a screenshot for easier access, but the best way to view it is through the zip.

Professor messaged me and he couldn't open this zipped file. Is it enough to submit just the PDF with the mockup or we need something from the zipped folder? I can resubmit it

**Comment by BeepDroid** [comment]
[Product Web Page.zip](https://github.com/IanTDuncan/MealTime/files/13111111/Product.Web.Page.zip)
Here's an updated storyboard utilizing aspects of material design. 
Backup PDF just in case.
Also have this for Android APK 
[Product Web Page (1).pdf](https://github.com/IanTDuncan/MealTime/files/13111118/Product.Web.Page.1.pdf)

**Comment by BeepDroid** [comment]
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/afd7d2e6-f86b-428f-b67b-c3bd3161095b)
(Screenshot is a little hard to read). With the program I used, we can interact with the buttons as if it were a fully compiled webpage. This should absolutely help us with compiling.

**Comment by bdshanks-28** [comment]
It's looking good now. You think we could show him and get some early feedback?

**Comment by IanTDuncan** [comment]
Looks pretty good, but I do think some of the UI colors could be more vibrant. Maybe we should lean away from the more pastel colors?

**Comment by aaleksandraristic** [comment]
This looks great so far! Nice work!
Let's show him and see what he thinks...
Also, I agree with Ian, I think we should use some more vibrant colors and be consistent with shapes, 

I kinda don't like Home page, I think we need something to be interesting, maybe different kind of food flying from the center of the page, behind the user registration text fields or something dynamic.
