### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#36]
**New explanation from Moodle!**
-----------------------------------------------------------
For our course, I am requiring each of you to familiarize yourselves with and utilize project management software. A recommended option is GitHub, which is widely used in the software development community.

Your Task:

If you already have an account on GitHub (or your chosen project management software), you may continue using it. If you don't have an account, please sign up.
Create a new repository for this course. Name it appropriately, e.g., "CS-CourseName-YourName".
As you work on assignments and projects, regularly push your updates to this repository.
What I Need From You:

----------------------------------------------------------

-> Option A: **Share the link** to your repository with me. Ensure that the repository is public or, if private, you've granted me access.
Option B: If you are using a different project management software and it allows exporting project data, please send me the exported file.
Remember, the goal is to get acquainted with tools that you'll often encounter in real-world software development scenarios. If you face any issues or have questions, please reach out.

**Comment by Cade5480** [comment]
I really do not know what this means, what does he even mean by "tool" and why am I having to upload my personal login/export from my personal system? 

If someone can explain this to me a little bit let me know because I am a little confused.

**Comment by aaleksandraristic** [comment]
@Cade5480  Let's ask him. I am not really sure what it means as well

**Comment by Cade5480** [comment]
He said he will rephrase it on Moodle, just provide credentials of GitHub is what he said so ill get on it soon

**Comment by Cade5480** [comment]
He wants the link to be shared so he can view our progress.

I made sure to make the repository public and i shared the link with him so he can view our repository.

**Comment by aaleksandraristic** [comment]
Awesome, thank you Cade!

**Comment by Cade5480** [comment]
Yes ma'am! I will be closing this issue!
