### ISSUE TITLE
Key Resources

### ISSUE THREAD

**Issue by IanTDuncan** [IanTDuncan/MealTime#4]
What Key Resources do our Value Propositions require?
Our Distribution Channels? Customer Relationships?
Revenue Streams?

**Comment by IanTDuncan** [comment]
One of our key resources, the food database located at [FoodData Central](https://fdc.nal.usda.gov/), is required for value propositions.

**Comment by IanTDuncan** [comment]
Revenue Streams:

 We start off with two option an initially paid app or an initially free app. If the app is paid, we'll have a steady stream of revenue as long as customers keep on buying the app. A free app, on the other hand, has can be supported by in-app ads and users can additionally pay to remove ads. Another option for the free app, is to lock features behind a subscription, therefore encouraging users to pay using the subscription. The last and least moral option is selling user's data, but I have obvious problems with this one.

**Comment by Cade5480** [comment]
Looks good so far!

**Comment by IanTDuncan** [comment]
Distribution Channels:

MealTime is an app designed to for "want" rather than "need" and as such will be focused on a niche, lifestyle market. Our cost-benefit ratio so far is undecided, but will be elaborated on later. Our product will be a standard one, mainly sold through the various mobile appstores to help reach a wide audience.

**Comment by bdshanks-28** [comment]
I think that having more convenient features being locked behind paywalls is the best bet there.

**Comment by BeepDroid** [comment]
Maybe an ad-free version would be available for purchase? That way we could have revenue from the ads from those who decide to put up with it for the free version, _and_ revenue from those who decide to pay to save themselves the headache. We could do this based on small monthly installments, maybe.

**Comment by bdshanks-28** [comment]
Monthly subscription is a good step in while using ads.

**Comment by Cade5480** [comment]
Looks good Ian, we can look into closing this issue soon!

**Comment by IanTDuncan** [comment]
### Key Resources Closing Comment

**What Key Resources do our Value Propositions require?**

Key resources are what allow our app to function effectively, I will outline the ones we have below.

1. Food nutrition information/data which will be pulled from [FoodData Central](https://fdc.nal.usda.gov/) which is maintained by the USDA
2. The app itself, contains the systems our customers will use to plan their meals
3. Our database of meals, will be used by the customer

**Distribution Channels**

- MealTime is an app designed for "want" rather than "need" and will be focused on a niche, lifestyle market.
- Our product will be a standard one, mainly sold through the various mobile app stores to help reach a wide audience.

**Revenue Streams**

- Our revenue steam will be a free app with ads 
- Users will be able to get rid of ads by paying a small monthly subscription

**Customer Relationship**

- Since customers will be able to input their own meals and recipes they will be able to share with other MealTime customers, this will be a co-creation relationship
- In time we hope to grow a community based on these customer inputs which will lead to a long-term relationship

**Comment by IanTDuncan** [comment]
### Key Resources Closing Comment


**Key Resources our Value Propositions require**

Key resources are what allow our app to function effectively, I will outline the ones we have below.

1. Food nutrition information/data which will be pulled from [FoodData Central](https://fdc.nal.usda.gov/) which is maintained by the USDA
2. The app itself, contains the systems our customers will use to plan their meals
3. Our database of meals, will be used by the customer

**Distribution Channels**

- MealTime is an app designed for "want" rather than "need" and will be focused on a niche, lifestyle market.
- Our product will be a standard one, mainly sold through the various mobile app stores to help reach a wide audience.

**Revenue Streams**

- Our revenue steam will be a free app with ads 
- Users will be able to get rid of ads by paying a small monthly subscription

**Customer Relationship**

- Since customers will be able to input their own meals and recipes they will be able to share with other MealTime customers, this will be a co-creation relationship
- In time we hope to grow a community based on these customer inputs which will lead to a long-term relationship

**Comment by aaleksandraristic** [comment]
Awesome job, everything looks good! I added this to the Business Canvas Model.
