### ISSUE TITLE
Gitlab CI/CD 

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#41]
-> Implement the installer to the code
	-> Security (code);
	-> Alpha program - channel 
   	   Beta program - very little info 
	-> Tokens, security controlsv

**Comment by IanTDuncan** [comment]
### App Installer
Last week we decided to switch from Swift to Android Studio to build our app. After developing a small calculator app over the weekend, I discovered that Android Studio has a built-in installer generator. Steps for how to are below

1. Build -> Generate Signed Bundles / APK(s) 
2. With the choice of Android App Bundle / APK choose APK
3. Generate security keys for the app, if it's your first time generating an APK, you'll have to make a folder to put the keys in

**I will try and find some official documentation on this when I have the time**
