### ISSUE TITLE
Grades Feedback

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#43]
The purpose of this would be to keep track who is doing what updates on specific issues that has to be changed.

**Comment by aaleksandraristic** [comment]
**Frades Feedback on October 9th:**

  1. Standup Submisson - Some of the standups were submitted just a few minutes before the class, which is considered late. 
                         -> Please make sure to submit your standups at least an hour before the class.
                         -> @aaleksandraristic has checked with a professor about this issue; the explanation is above! - DONE!
                                         
  2. Elevator Test Statement - Introduction, Redundancy, Clarity, Specificity, Value Proposition
                         -> e.g. "Looking for a smarter way to embrace a healthy eating lifestyle? MealTime is your solution. Our app 
                                     empowers users to easily track their daily food intake, monitor nutritional values, and witness the 
                                     transformative benefits of healthier choices."
                                     
                         -> @Cade5480 has updated the Elevator Test Statement and submitted it on Moodle - DONE!
                                     
  3. Storyboard - Needs professional and standardized format.
                          -> @BeepDroid is going to update the Storyboard -
  
  4. Business Plan - Income, Expenses, Profit 
                          -> @aaleksandraristic summarized the expenses and expected income and submitted the PDF - DONE!
  
  6. Envisoning Presentation - Submit it!
                          -> @Cade5480 has submitted the presentation - DONE!

**Comment by Cade5480** [comment]
Way to be on top of this!

**Comment by bdshanks-28** [comment]
Woo! Thanks for being on top of this Alex.
