### ISSUE TITLE
Speculating Presentation

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#45]
October Milestone - issues

- I will write down all the info, that we need to include in our presentation after class tomorrow.

**Comment by Cade5480** [comment]
https://docs.google.com/presentation/d/1Ez-Z72p6Dx96mGi_zCKYMofxTSc-4ROg4fCEwboQ180/edit#slide=id.g292f3c584b6_0_0

Link to Speculating Presentation
