### ISSUE TITLE
CI Setup

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#47]
Here is the PDF for the Pipeline:
[Agile development.pdf](https://github.com/IanTDuncan/MealTime/files/13112456/Agile.development.pdf)

Divided into the following issues:

- **Build Environment**

- **Pipeline Configuration**

**Comment by BeepDroid** [comment]
For Build Environment: 
Utilizing GitLab CI, we can configure a CI
runner that will pick up builds. Runners are
isolated virtual machines that runs the job,
then sends the results right back to that
GitLab instance.

For Pipeline Configuration:
We can create a file to define the jobs between CI
and CD; .gitlab-ci.ym

Also from the pipeline. Will go in depth and post sources used for this soon.

**Comment by aaleksandraristic** [comment]
CI Setup
-----------------------
Setting up Continuous Integration (CI) helps us to automate and streamline the development process, ensuring that our code is built, tested, and deployed consistently. Here are the key steps for setting up CI:

1. What is CI?
Continuous Integration (CI) is a software development practice where code changes are automatically built, tested, and integrated into the shared codebase frequently. The primary goal of CI is to catch and fix issues early in the development cycle, improve code quality, and ensure that the application remains in a deployable state.

2. Choose a CI/CD Service:
We'll need a CI/CD service to set up the CI pipeline -> GitHub Actions, GitLab CI/CD, Travis CI, CircleCI, Jenkins...

3. Create a Configuration File:
Most CI/CD services use configuration files to define the build and deployment process. We'll need to create a configuration file that specifies what our CI pipeline should do. This file is often called .yml (for example, .gitlab-ci.yml or .github/workflows/main.yml) and is stored in project's repository.

4. Define the CI Pipeline:
The CI pipeline typically includes the following steps:

- Build: This step compiles code and prepares it for testing and deployment.
- Test: Run unit tests, integration tests, and other types of testing to ensure the quality and correctness of the code.
- Package: Create deployable artifacts, such as application bundles, containers, or distribution packages.
- Deploy: If we're deploying to a server or cloud service, this step automates the deployment process.
- Notify: Send notifications or alerts if the pipeline succeeds or fails.

5. Environment Configuration:
Configure CI environment with the necessary dependencies and environment variables. For example, our app relies on a database, so we have to make sure that the CI environment has access to it.

6. Monitor and Reporting:
Set up monitoring and reporting to track the status and progress of the  CI pipeline. 

9. Triggering CI:
Once the CI pipeline is defined and configured, it can be triggered automatically whenever code changes are pushed to the version control repository. We can also manually trigger the pipeline if needed.

11. Documentation:
Document CI setup and processes so that all our team members can understand and contribute to the pipeline.

**Comment by aaleksandraristic** [comment]
GitHub - Building Environment
-----------------------------------------------
This might help us:  https://www.youtube.com/watch?v=5XfgT9A9PHw&ab_channel=MickeyGousset

**Comment by aaleksandraristic** [comment]
GitHub - Pipeline Configuration
-----------------------------------------------------
Thie one can be useful as well: https://www.youtube.com/watch?v=euEkYEFCrI8&ab_channel=Thetips4you

**Comment by BeepDroid** [comment]
[Here's an explanation of a CI in Android Studio](https://developer.android.com/studio/projects/continuous-integration), as well as an explanation of what a CI runner is: "A runner is an isolated (virtual) machine that picks up builds through the coordinator API of GitLab CI." While this does utilize GitLab, GitLab and GitHub can be integrated together, allowing for seamless CI/CD from git repos. 

[Here's a tutorial of how to set up a CI Runner for Android Studios](https://about.gitlab.com/blog/2018/10/24/setting-up-gitlab-ci-for-android-projects/)

**Comment by bdshanks-28** [comment]
So far it looks like we will be using CI in android studio that integrates GitLab which will also be integrated with GitHub? Am I following this correctly so far?

**Comment by BeepDroid** [comment]
Exactly right!
