### ISSUE TITLE
CD Pipeline

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#49]
Here is the PDF for the Pipeline:
[Agile development.pdf](https://github.com/IanTDuncan/MealTime/files/13112456/Agile.development.pdf)

Divided into the following issues:

- **Deploy Staging Environment** 

- **Staging Environment Testing Phase, allow a few testers access**

- **Use UI Automator or Jetpack Compose*

- **Deploy Production Stage**

**Comment by BeepDroid** [comment]
For the staging environment, I found a really good resource.

[This is basically a step-by-step guide](https://medium.com/easyfundraising-org-uk/setting-up-for-different-environments-in-android-studio-using-build-variants-product-756fdf8d47fb)  for setting up a staging environment through android studio.

**Comment by BeepDroid** [comment]
As for automated UI testing, we could use Jetpack Compose, as it includes API that allows writing and setting up of automated testing. [This has some more information](https://developer.android.com/training/testing/instrumented-tests/ui-tests), and shows some other reources that provide the UI for setting up testing. 

We can also look at [UI Automator](https://developer.android.com/training/testing/other-components/ui-automator) .

**Comment by BeepDroid** [comment]
[Here's something for defining a production stage for us](https://www.pagerduty.com/resources/learn/what-is-production-environment/) , this will help with building and understanding the concept.

And here is a [article that outlines the difference between each stage.](https://www.servermania.com/kb/articles/production-development-staging)
