### ISSUE TITLE
Value Propositions

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#5]
What value do we deliver to the customer?
Which one of our customer's problems are we helping to solve?
What bundles of products and services are we offering to each Customer Segment?
Which customer needs are we satisfying?

**Comment by Cade5480** [comment]
We will be delivering an option to our customer to track their caloric intake along with other macros through our application.

We are making a solution for our customers to be able to lose weight by eating healthier.

We are offering a calorie tracker, a grocery list to view certain foods and be able to choose and select which ones you have consumed as well as generate a meal for you along with the calories and other macros all through our application.

Our team will be satisfying the need of people who wish to track their caloric intake and people who wish to live a healthier life as well as satisfy the needs of people who do not want to get pulled into a monthly calorie tracker subscription.

**Comment by bdshanks-28** [comment]
Doing good!

**Comment by aaleksandraristic** [comment]
I agree, well said!

**Comment by IanTDuncan** [comment]
Everything looks good so far.

**Comment by BeepDroid** [comment]
Fantastic overview of the features!

**Comment by Cade5480** [comment]
Thanks for the feedback! I will be closing this issue!

**Comment by aaleksandraristic** [comment]
I added this to the Business Canvas Model. Good job!
