### ISSUE TITLE
Build Stage with Android Studio

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#50]

**Comment by IanTDuncan** [comment]
### What Is The Build Stage?
The build stage of the CI/CD Pipeline draws source code from a repository, establishes links to relevant libraries, modules and dependencies, and compiles all these components into an executable file. Moreover, during the build stage, the system often also handles tasks like resolving dependencies, compiling languages, and bundling assets. The outcome of this stage is an artifact that can be deployed in the next stages.

Another crucial aspect of the build stage is the execution of preliminary tests, often unit tests or static code analysis. These tests, which focus on individual components of the application, ensure that the code’s basic correctness and quality are upheld. If these tests or the build process itself fails, the pipeline execution halts (the build “breaks”), and developers are notified. 

**Sources:**

> https://codefresh.io/learn/ci-cd-pipelines/ci-cd-process-flow-stages-and-critical-best-practices/

> https://www.techtarget.com/searchsoftwarequality/CI-CD-pipelines-explained-Everything-you-need-to-know

> https://semaphoreci.com/blog/build-stage

### Goal(s) For November

- Implement the various development tools with Android Studio
- Develop a working build for the pipeline

**Comment by IanTDuncan** [comment]
### Build Stage Tools And Their Compatibility

**Tools**

1. GitHub

> GitHub hosts repositories where developers store and manage source code, enabling collaboration, version control, and issue tracking. GitHub doesn't directly handle databases or back-end services; rather, it's focused on managing code repositories and facilitating collaborative development.

2. SQL Databases

> SQL databases are used for structured data storage and retrieval. They follow a relational model and are ideal for applications where data integrity, complex relationships between data entities, and SQL querying are crucial.

3. Android Studio

> Android Studio is an Integrated Development Environment (IDE) specifically tailored for Android app development. It plays a significant role in the build stage by providing a comprehensive set of tools and features to facilitate the creation, compilation, testing, and packaging of Android applications.

4. Firebase

> Firebase is a platform offering various services like real-time databases, authentication, cloud storage, and more. It's primarily used for back-end services and hosting, enabling developers to build and manage applications without setting up traditional server infrastructure. Firebase can store data, handle user authentication, and provide back-end functionalities.

**Potential Tool Compatibility Issues**
Firebase and SQL Databases while not occupying the same position in application development do share some overlap in terms of databases.

- Firebase provides a NoSQL database in the form of the Firebase Realtime Database or Firestore, which are document-based databases suitable for real-time data synchronization and easy scalability. 
- SQL databases, on the other hand, operate on a structured query language and follow a relational model. These databases organize data into tables with predefined schemas and support complex queries using SQL.

If we are to use both SQL and Firebase databases we need to identify where to best use those databases lest we cause redundancies in our application.

**Comment by bdshanks-28** [comment]
https://canieatit.co.uk/product-and-barcode-api/   --- Pros: can scan barcodes (this means we would have to figure out how to use the camera)

https://chompthis.com/api/   --- Pros: Has more of a focus on processed and packaged foods.

https://developer.edamam.com/edamam-nutrition-api --- (**Might be the best?**) Pros: Can submit a whole text of a recipe and the API breaks down the caloric content of the whole recipe rather than one by one.

https://fdc.nal.usda.gov/api-guide.html --- Pros: Connected to the US Department of Agriculture database and constantly updated. Has two endpoints: the Food Search endpoint, which returns foods that match desired search criteria, and the Food Details endpoint, which returns details on a particular food. Also has the most common foods publicly available (Most likely the most reliable?)

**Comment by IanTDuncan** [comment]
- [Nutritionix API](https://www.nutritionix.com/business/api): Offers a vast database of food items, their nutritional values, and also provides a nutrition analysis. It's commonly used for building nutrition-related apps.
- [Open Food Facts API](https://openfoodfacts.github.io/openfoodfacts-server/api/#overview): An open database with information on food products from around the world. It contains nutritional information, ingredients, and more.
- [FatSecret Platform API](https://platform.fatsecret.com/platform-api): Provides access to a massive food, nutrition, and recipe database. It includes nutritional information, food logging, and more.
- [Spoonacular API](https://spoonacular.com/food-api): Offers a wide range of food-related data, including recipes, meal planning, and nutrition information.
