### ISSUE TITLE
Unit and Continuous Testing

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#51]

**Comment by Cade5480** [comment]
Unit testing involves testing individual units or components of a software application in isolation. Units are the smallest testable parts of an application, such as functions, methods, or classes. The goal is to ensure that each unit functions correctly as designed. In summary, app unit testing is about checking the smallest building blocks of an application to ensure they work as expected, contributing to a more robust and reliable overall software system.

**Comment by Cade5480** [comment]
Continuous testing is a software development practice that involves running automated tests throughout the entire development lifecycle. The idea is to constantly assess the code's quality and functionality, ensuring that any changes or additions to the codebase don't introduce new issues.

This approach integrates testing seamlessly into the development process, from initial coding to deployment. Continuous testing helps catch and address issues early on, promoting a more agile and reliable development environment. It's a key element of continuous integration and continuous delivery (CI/CD) pipelines, contributing to faster and more efficient software delivery with higher confidence in its quality.
