### ISSUE TITLE
Staging Environment Testing Phase

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#55]

**Comment by bdshanks-28** [comment]
https://www.servermania.com/kb/articles/production-development-staging

Some article explaining differences for me to refer back to so I don't get mixed up.

**Comment by bdshanks-28** [comment]
https://www.bunnyshell.com/blog/what-is-a-staging-environment/

A small description of what staging environments are. Very clear about what to look for when making one, def gonna go back to this time and time again for now.

**Comment by bdshanks-28** [comment]
If the test fails, how far back do we go? Do we hop back to source code control? Things to think about based on what we went over post presentation, give me your thoughts.
