### ISSUE TITLE
Cost Structure

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#6]
What are the most important costs inherent in our business model?
Which Key Resources are most expensive?
Which Key Activities are most expensive?

**Comment by aaleksandraristic** [comment]
I started working on question #3: Which Key Activities are most expensive?

**Comment by aaleksandraristic** [comment]
I am working on a question #1 - What are the most important costs inherent in our business model?

**Comment by Cade5480** [comment]
I will have to get with you on our Key Resources, i have a list of some right now from my issue

**Comment by aaleksandraristic** [comment]
I totally forgot to upload it here. I will do it today when I get home. 
Also, I have kinda a lot of text, so I will shorten it before submission.

**Comment by Cade5480** [comment]
Ok so our Key Resources are going to be Slack (using this for communication), GitHub, Swift, and SQL Server. All of these applications are gonna be free of charge so we are not having to spend any money on these. Although to publish an app on the google play store for android, we may or may not have to pay a small amount using the google play console.

**Comment by Cade5480** [comment]
Yeah of course its no problem at all!

**Comment by aaleksandraristic** [comment]
Oh okay, good to know. I will include that. I did basically according to other similar businesses.

**Comment by bdshanks-28** [comment]
> Ok so our Key Resources are going to be Slack (using this for communication), GitHub, Swift, and SQL Server. All of these applications are gonna be free of charge so we are not having to spend any money on these. Although to publish an app on the google play store for android, we may or may not have to pay a small amount using the google play console.

I thought we were using sqlite as the sql integration for swift?

**Comment by aaleksandraristic** [comment]
**1. What are the most important costs inherent in our business model?**

**Answer:** 
**Fixed costs** - These are costs that remain relatively constant regardless of the level of production or sales.
    * Publishing and keeping an app on the  google play store for android or apple store for ios (monthly/yearly)
    * Salaries for each employee
    * Utilities such as internet, available software, electricity 
    
**Variable costs** - These costs fluctuate based on the level of production or sales.
    * Raw data resources - 
    * App development costs - development, updating, editing...
    * Cost of the app - Our app should be free right? But maybe some specific features could require the subscription (such as 
       ML predictions or smth like that)

**Operating costs** - These are ongoing expenses essential for running the day-to-day operations.
    * Marketing and Advertising - promotions and attract brand visibility
    * Research and Development - developing new features; improving existing ones
    * IT Infrastructure - Costs associated with maintaining computer systems and software
    
**Unpredictable costs** - costs that might be changed in the future

**I will continue working on this question in order to see if we are missing something**

**Comment by aaleksandraristic** [comment]
> > Ok so our Key Resources are going to be Slack (using this for communication), GitHub, Swift, and SQL Server. All of these applications are gonna be free of charge so we are not having to spend any money on these. Although to publish an app on the google play store for android, we may or may not have to pay a small amount using the google play console.
> 
> I thought we were using sqlite as the sql integration for swift?

Let me know what works best for you to connect with. I would prefer sql server since we could create specific stored procedures and triggers (I saw that those are not allowed in sqlit). But, again, if sqllite works better then I will use that one. What do you guys think?

**Comment by aaleksandraristic** [comment]
**3. Which Key Activities are most expensive?**

**Answer:**
**Research and Development** 
     *Research and development of new app features
     *Updates of the existing version
     *Quality checks - both frontend (software development check) and backend (data quality check)
     *Cost checks - we want to reduce or minimize costs and to achieve a goal
     *Design cost
 
**Problem Solving** -  finding a solution to individual problems faced by both customers and developers
     * Project Management 
     * Data Cleaning and Analysing
     * Software Development
     * Testing
     
**Platform/network** - networks, combination platforms, software.

**Comment by aaleksandraristic** [comment]
**2. Which Key Resources are most expensive?**

**Answer:**
**Human Resources** - people power
    *Employees - software engineers, data analysts, project manager
    *Key Partners - USADA, ...

**Financial Resources** - provide the necessary capital for developing and maintaining the app
    *Investments, grants, lines of credit
    *Branding – design, logo, graphics
    *App Store Hosting - Google Play Store  
    *Employees – money for salaries, tax, healthcare…
    *Marketing – B2C (business to customer) and market sector (food, health track, time-saving app)
    *Raw Data – for now, we are using free public data that we have found on the Internet, but there is a threat if the access 
     becomes limited then we have to pay for it.  
    
**Intellectual Resources** - These are intangible resources like:
    *If we develop some innovative idea/feature we could get our own patent 
    *We have our own brand - MealTime
    *Partnerships

**Digital resources**
    *Software/applications - Slack (communication), GitHub, Swift, and Microsoft SQL Server + ... (maybe something else)
    *Online Data Source - USADA

**Comment by aaleksandraristic** [comment]
Hey guys, what do you think about the answers above? 

 * Please let me know if there is something else that you think should be added or removed. :)

**Comment by Cade5480** [comment]
There’s not a single thing I can find that I disagree with, looks good Aleks!

**Comment by IanTDuncan** [comment]
I agree everything looks great!

**Comment by BeepDroid** [comment]
Great work!! I can't see anything I disagree with!

**Comment by bdshanks-28** [comment]
I think it's well made and I see no issues!

**Comment by aaleksandraristic** [comment]
I added this to the Business Canvas Model.
