### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by BeepDroid** [IanTDuncan/MealTime#63]
For keeping track of the terms and conditions progress and ensuring we are all aware and on board with what is being included in it. Daft updates, discussion, and final version goes here before implementation.

**Comment by BeepDroid** [comment]
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/42e4fec0-a5dd-4435-ba80-443ab91e0db5)
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/586f45bb-e689-4241-bcd9-98615c4d6c31)
The beginnins of our Terms and Conditions. Anything I should edit, exnay, or otherwise change?

**Comment by aaleksandraristic** [comment]
Everything looks good so far! Great job Kerry!

**Comment by BeepDroid** [comment]
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/19966023-6bde-4db9-ba9c-b7eb729bfaad)
How's our prohibited activites looking?

**Comment by aaleksandraristic** [comment]
This looks good to me! I don't think anything else should be added.

**Comment by BeepDroid** [comment]
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/aca60a99-eeba-4b07-ae02-e20347c65b76)
![image](https://github.com/IanTDuncan/MealTime/assets/71675347/0a391989-ec54-4788-a5f7-2e22ef807642)
Some updates to our terms and conditions, I'll have the first draft ready for review by Tuesday night!

**Comment by BeepDroid** [comment]
https://docs.google.com/document/d/19lHDUvVawh3nqcWvHw1AxgqRi6ODnzgh8iV3tZhtbps/edit?usp=sharing

Alright, draft is up!
@aaleksandraristic @Cade5480 @bdshanks-28 @IanTDuncan

**Comment by aaleksandraristic** [comment]
Wow, I didn't expect it this long! Great job Kerry!

**Comment by BeepDroid** [comment]
As the drafts have been reviewed and approved for app inclusion as they are, and the team has already approved closing of this ticket, I'm ending this issue as completed. 

If an update needs to be made in the future, a new ticket will be created for it. 

Final Notes: 

Team has access to link for the entirety of the document. 
Cade has access to document for editing purposes as he is handling app implementation. 
Access for editing can and will be given upon email request from the document.
