### ISSUE TITLE
UI/UX design and experience

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#65]
CURRENT ISSUE
------------------------------------

CLEAN UP OF XML PAGES
------------------------------------

Description: 
----------------------------

Clean up the many xml files we have and are redundant or not going to be used.

Steps to Reproduce: 
-------------------------------

We can open the project folder and see there are a lot of xml files in there, but not all are absolutely necessary.

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

This is using Kotlin in an xml file format being edited by Android Studio IDE.

For Issue Resolution:
------------------------------

Discuss with Cade before removing files he might be directing to and help direct him to the correct files so we may remove the unnecessary xml pages.

For Investigations/Research:
------------------------------------------

I want to clean up the xml files in the project that may be redundant and fix the naming style. However I will need to discuss with @Cade5480 in order to help change which buttons direct to which page so deleting a page he is pointing to and end up not being able to compile the program.

Current Status: 
------------------------

Completed

**Comment by bdshanks-28** [comment]
[Sources for me ](https://developer.android.com/studio/write/layout-editor)to use when editing the xml files.

**Comment by bdshanks-28** [comment]
Edited several buttons and backend xml to commit to the repository for everyone else to see.

**Comment by bdshanks-28** [comment]
Looked over added features Kerry added. Did want to ask later but can we go ahead and put in privacy policy and other things like static text into the correct pages or do those need more work @aaleksandraristic and @BeepDroid?

**Comment by aaleksandraristic** [comment]
Yeah, I guess they're completely done, but let's check with @BeepDroid?

**Comment by bdshanks-28** [comment]
CLEAN UP OF XML PAGES
------------------------------------

Description: 
----------------------------

Clean up the many xml files we have and are redundant or not going to be used.

Steps to Reproduce: 
-------------------------------

We can open the project folder and see there are a lot of xml files in there, but not all are absolutely necessary.

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

This is using Kotlin in an xml file format being edited by Android Studio IDE.

For Issue Resolution:
------------------------------

Discuss with Cade before removing files he might be directing to and help direct him to the correct files so we may remove the unnecessary xml pages.

For Investigations/Research:
------------------------------------------

I want to clean up the xml files in the project that may be redundant and fix the naming style. However I will need to discuss with @Cade5480 in order to help change which buttons direct to which page so deleting a page he is pointing to and end up not being able to compile the program.

Current Status: 
------------------------

In progress

**Comment by aaleksandraristic** [comment]
@bdshanks-28 Could you please put the formatted comment into issue header or description section? So it will pop up as a first thing when we open the issue. Thank you!
