### ISSUE TITLE
Backend Development

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#66]
Creating this issue to keep track of any additions or changes to backend development. Any changes I make I will log inside of this issue or any additions I make, I will do the same.

**Comment by Cade5480** [comment]
**TICKET #1**  
Task 1 - add back button to the registration page
Task 2 - add logic so when clicked you return to the login page

**Comment by aaleksandraristic** [comment]
Hey Cade, there is an option here to create a track list, it might help you to keep track of what has been done and what is left for later. Just my suggestion for easier tracking. Please also write down everything that you are working on :)

**Comment by Cade5480** [comment]
I added logic to the xml manifest class so that when you click login or register it knows to bring up the Main Menu or the Registration page. I also made a change to where we no longer need the Login class and put it in the Main Activity class as the Main Activity and Login were doing basically the same thing. I also fixed an issue where you were able to login without filling out the user information and added popups for the login being successful or when they are empty as they were added before but not showing properly.

**Comment by aaleksandraristic** [comment]
Amazing work Cade, thank you for keeping me and everything else posted!

**Comment by Cade5480** [comment]
Currently have Ticket 2 complete, waiting to get with Kerrigan to get my committing issue fixed

**Comment by Cade5480** [comment]
Tickets 1, 2, and 3 have been completed, will look into opening more tickets for myself
