### ISSUE TITLE
Edamam API Hub

### ISSUE THREAD

**Issue by IanTDuncan** [IanTDuncan/MealTime#67]
### What This Contains:

- Links to the Edamam APIs we'll be using
- Links to the documentation for the APIs
- Dependencies needed for the APIs to work
- Why that dependency is being used
- Links to the aforementioned dependencies
- Reasoning for why an API is where in the code

**Additional Software Relevant to the APIs:**
Dependency/Library: [Retrofit](https://square.github.io/retrofit/)

**Comment by IanTDuncan** [comment]
### [Edamam Food Database API](https://developer.edamam.com/food-database-api)
[Documentation](https://developer.edamam.com/food-database-api-docs)

Dependency/Library: [Retrofit](https://square.github.io/retrofit/)

- Started with the database first due to my understanding of it being a central component of the app
- Plan to first instantialize it under the Grocery List page
- Need to use a networking library to handle the HTTP requests since Android Studio cannot do it directly

**Comment by aaleksandraristic** [comment]
Hey Ian, I wanted to check with you how we gonna do API for the database? My next step is to initialize Firebase in the App and see if there are any other things that need to be set up. The next step after that would be pulling the data from an API.

**Comment by IanTDuncan** [comment]
@aaleksandraristic You could maybe work on pulling/storing account data for users since that is going to be one of the first things users will have to make in the app

**Comment by aaleksandraristic** [comment]
Yes, I will start doing that part first then.

**Comment by IanTDuncan** [comment]
### [Edamam Recipe Search API](https://developer.edamam.com/edamam-recipe-api)
[Documentation](https://developer.edamam.com/edamam-docs-recipe-api)

- Edamam Meal Planner is dependent on Edamam Recipe Search

**Comment by IanTDuncan** [comment]
### [Edamam Meal Planner API](https://developer.edamam.com/meal-planner-api)
[Documentation](https://developer.edamam.com/edamam-docs-meal-planner-api)

**Comment by IanTDuncan** [comment]
Closing this issue as it isn't relevant to app anymore
