### ISSUE TITLE
UI/UX - account_about_activity.xml

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#68]
Created the page.

**Comment by bdshanks-28** [comment]
Extending my due date to Wednesday. Currently have not worked on any code, but I have been drafting a mock up on paper.

**Comment by bdshanks-28** [comment]
Code changes will be posted tomorrow.

Changes:
Created the relative view
Ended up discussing with my team and decided to play buttons that will be hyperlinks to our policy and security terms.
Added back button to return to account main menu
Organized the buttons to match what other pages had

**Comment by aaleksandraristic** [comment]
Thank you for the update. Could you please use the format that the professor gave us so we can all be aware of what is this issue about (you don't have to explain in details), but just try to use the format. Thank you, great job so far!

**Comment by bdshanks-28** [comment]
Description: There was no issue to keep the relative view format from functioning in the xml file.

current code:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    
    <Button
        android:id="@+id/button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="20dp"
        android:layout_marginTop="20dp"
        android:text="Back" />

    <Button
        android:id="@+id/buttonForTerms"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="100dp"
        android:layout_marginTop="100dp"
        android:text="Terms and Conditions" />

    <Button
        android:id="@+id/privacyPolicyButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="50dp"
        android:layout_marginTop="50dp"
        android:text="Privacy Policy and Security Terms" />

</LinearLayout>
