### ISSUE TITLE
UI/UX - activity_login.xml

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#71]
Created the xml page, added a text input box for username and password and two buttons, one for a log in, and one to register to redirect to a register page.

**Comment by bdshanks-28** [comment]
Reformatted buttons to be more centered on the screen and adjusted everything for a phone keyboard popping up on screen.

**Comment by bdshanks-28** [comment]
CURRENT CODE FOR COMPLETED UX ELEMENTS

<?xml version="1.0" encoding="utf-8"?>



<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_centerHorizontal="true"
    android:layout_gravity="center"
    android:gravity="center|top|center_vertical">

    <EditText
        android:id="@+id/editTextUsername"
        android:layout_width="372dp"
        android:layout_height="wrap_content"
        android:layout_centerInParent="false"
        android:layout_centerHorizontal="true"
        android:layout_gravity="center"
        android:layout_marginTop="50dp"
        android:hint="Username"
        android:minHeight="48dp" />

    <EditText
        android:id="@+id/editTextPassword"
        android:layout_width="372dp"
        android:layout_height="wrap_content"
        android:layout_alignWithParentIfMissing="true"
        android:layout_below="@id/editTextUsername"
        android:layout_centerInParent="true"
        android:layout_gravity="center"
        android:layout_marginTop="18dp"
        android:hint="Password"
        android:inputType="textPassword"
        android:minHeight="48dp" />

    <Button
        android:id="@+id/buttonLogin"
        android:layout_width="178dp"
        android:layout_height="wrap_content"
        android:layout_alignWithParentIfMissing="false"
        android:layout_below="@id/editTextPassword"
        android:layout_centerInParent="true"
        android:layout_marginTop="19dp"
        android:gravity="center"
        android:text="Login" />

    <Button
        android:id="@+id/buttonRegisterPage"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonLogin"
        android:layout_marginTop="17dp"
        android:text="Register" />

</RelativeLayout>

**Comment by aaleksandraristic** [comment]
Hey Brandon I see that this issue is marked as done in the roadmap, should I close this issue?

**Comment by bdshanks-28** [comment]
Yes this should be closed, sorry for the delayed response.
