### ISSUE TITLE
API - Edamam Meal Planner

### ISSUE THREAD

**Issue by IanTDuncan** [IanTDuncan/MealTime#84]
### API - Edamam Meal Planner

__________________________________________________

### Description:

__________________________________________________
This is an issue for everything relating to Edamam Meal Planner API, an HTTP based API. Research and actual code is in comments appropriately labeled so. It uses the MealPlanner class to send the HTTP request with the parameters and the SearchResult class returns the results of the recipe search based on the aforementioned parameters.

### Steps To Reproduce:

_________________________________________________

1. Add dependencies for all necessary imports into the build.gradle.kts class
2. Create the MealPlanner class and add all the necessary methods 
3. Create the SearchResult class and add all the necessary classes it depends on

### Expected Behavior vs Actual Behavior:

_________________________________________________
**Expected Behavior:** Take parameters from user input such as calories, food types, or allergies send it, attach that to the Edamam Meal Planner API and then take the recipes/food that are returned by the API and display them.

**Actual Behavior:** While many of the systems are in place to allow most of the above to happen UI/UX integration has not begun.

### Code Snippets:

_________________________________________________
Below in separate comments.

### Environment Details:

_________________________________________________
Operating System: Windows 11
Firebase SDK Version: 23.0.0
Kotlin Version: 1.5.21
Android Studio Version: 4.2.1
Gradle Version: 7.0.2

### Issue Resolution:

Marking this issue as completed due to #129 and MealTime switching to Spoonacular

_________________________________________________
N/A

### Current Status: CLOSED

________________________________________________

**Comment by IanTDuncan** [comment]
Forgot to add this last night(02/07/2024) after I worked on it, but I essentially downloaded the .json file from [/api/recipes/v2/by-uri](https://developer.edamam.com/edamam-docs-recipe-api#/) under Edamam Recipe Search

Essentially Edamam Meal Planner uses the "Search By Recipe URI" access point in Edamam Recipe Search API

**Comment by aaleksandraristic** [comment]
Thank you for the update!

**Comment by BeepDroid** [comment]
**Description:**  So, the problem that's being had here is the fact that the Edamam Meal Planner API/Recipe Search functionality is only available to us in an HTTPS scheme, something neither I nor Ian have worked with before, and he's asked my help in figuring out where and how to implement it correctly despite its restrictions. 

**Initial Findings:** I've no code snippets to show, but I do have some resources I've gathered for reference and consideration while looking into how to solve this. I've already shared these with Ian in a private chat, but I'm posting these here for team reference and for he and I to have easier access: 

[Creating Deep Links to add App Content](https://developer.android.com/training/app-links/deep-linking) - This was one of the first references to come up during my search. It seems to be an explanaition of how to utilize HTTPS schemes in code, creating deep links in Android Studio in order to pull App content into your project. 

[A Stackoverflow post about the Deep Linking only working with HTTP and how to fix that](https://stackoverflow.com/questions/46680946/android-deep-linking-doesnt-work-with-http-https-scheme) - This came up almost immediately after, seems like a very good resource in the case we run into that issue! 

[Another Stackoverflow about a similiar issue](https://stackoverflow.com/questions/39486852/android-deep-linking-schema-match-both-http-and-https) - It's regarding the same HTTP/HTTPS deep link problem, but I always like to have mulitple references for a problem, just in the case the first fix doesn't work. 

**Steps for investigation:** 

- The first step will be going over these resources more thoroughly and seeing what we can do with the information outlined for us. 
- Ian said he is going to attempt to make code based off an HTTPS database he found, and we'll see the results with that, then continue on from there and see if a new tactic like those outlined above will be of any help. 

**Expected Outcome:** The beginning implementation of this API and figuring out how to interact with it!

**Comment by IanTDuncan** [comment]
`public class MealPlanner extends AppCompatActivity{

    OkHttpClient client;
    String mealPlan = "https://api.edamam.com/api/meal-planner/v1";

    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        client = new OkHttpClient();
    }

    public void get(){
        Request request = new Request.Builder().url(mealPlan).build();
        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(@NonNull Call call, @NonNull IOException e) {
                e.printStackTrace();
            }

            @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) throws IOException {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        
                    }
                });
            }
        });
    }

}`

This is just the basic framework for general http requests through Android Studio. I'll go back and refine it tomorrow while also adding everything pertaining to the Edamam Meal Planner

**Comment by IanTDuncan** [comment]
### Research For HTTP Requests

**Objective:** The objective of my research was to figure out how to send HTTP requests suited for Android Studio and Java. Additionally, the type of HTTP request I needed to build had to include a POST method, an HTTP method designed to send loads of data to a server from a specified resource. The POST method is used by the Edamam Meal Planner and is thus required.

**Initial Findings:** My initial findings were frustrating and frequently fruitless due to outdated information, divided opinions on which HTTP requesting service is best, and influencers promoting various differing HTTP request services. As a result, the previous code I posted above is not entirely suited for our app. On the other hand, I was able to grasp what HTTP requests were, what methods and classes were generally included when making one, and what a POST method is.

Eventually, after much more searching and some help from a classmate, I was able to find some helpful links:

- https://stackoverflow.com/questions/1359689/how-to-send-http-request-in-java
- https://stackoverflow.com/questions/3324717/sending-http-post-request-in-java

The 1st of the aforementioned links is for a general HTTP request in Java while the 2nd is for POST methods in Java.

> I did have to "translate" the POST link to a different version since Android Studio has since updated to have its own version of sending HTTP requests.

**Steps For Investigation:**

1. Instead of looking for HTTP requests specifically made for Android Studio, look for HTTP requests made for Java
2. Research POST methods and make sure the HTTP request that is being worked on includes them
3. Finally make sure the information that the answers the code is being based on is modern/updated

**Expected Outcome:** A working HTTP request class suitable to use with Edamam Meal Planner

**Comment by IanTDuncan** [comment]
### Updated Code for HTTP Framework
**Description:** This is updated/reworked code that is much more cohesive and includes POST method support. Is based on the code in these [two](https://stackoverflow.com/questions/1359689/how-to-send-http-request-in-java) [links](https://stackoverflow.com/questions/3324717/sending-http-post-request-in-java).

- Errors: Had to adjust the code in the first link to make it compatible with Android Studio. Also had to reduce the array dimensions in one of the links to make it appropriate for our app.

**Steps To Reproduce:**

1. Create the Java Class, "MealPlanner"
2. Add any necessary dependencies to the build.gradle.kts class
3. Import the aforementioned dependencies into the MealPlanner class
4. Create the necessary methods and classes used in the code

**Expected vs Actual Behavior:** 

- Expected Behavior: The expected behavior is to send an HTTP request using a POST method to the specified URL.
- Actual Behavior: The actual behavior is that an error pops up when referencing a commented-out behavior, but we're not sure we're going to use this behavior as we need to integrate the UI/UX first to make sure

**Code Snippet:**

`package com.example.mealtime1.APIs;

import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Arrays;
import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;

public class MealPlanner{

    public static String executePost(String targetURL, String urlParameters) {
        HttpURLConnection connection = null;
        targetURL = "https://api.edamam.com/api/meal-planner/v1";

        try {
            //Create connection
            URL url = new URL(targetURL);
            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Content-Type",
                    "application/x-www-form-urlencoded");

            connection.setRequestProperty("Content-Length",
                    Integer.toString(urlParameters.getBytes().length));
            connection.setRequestProperty("Content-Language", "en-US");

            connection.setUseCaches(false);
            connection.setDoOutput(true);

            String[] ParamString;
            String punch = "punch";
            ParamString =  new String[] {punch, "password"};

            ArrayList<String> params = new ArrayList<String>();
            params.addAll(Arrays.asList(ParamString));
            String paramsString = getParamsString(params);

            //Send request
            DataOutputStream wr = new DataOutputStream (
                    connection.getOutputStream());
            wr.writeBytes(urlParameters);
            wr.close();

            //Get Response
            InputStream is = connection.getInputStream();
            BufferedReader rd = new BufferedReader(new InputStreamReader(is));
            StringBuilder response = new StringBuilder(); // or StringBuffer if Java version 5+
            String line;
            while ((line = rd.readLine()) != null) {
                response.append(line);
                response.append('\r');
            }
            rd.close();
            return response.toString();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        } finally {
            if (connection != null) {
                connection.disconnect();
            }
        }
    }

//    private static String getParamsString(ArrayList<String> params) throws UnsupportedEncodingException {
//        StringBuilder result = new StringBuilder();
//        boolean first = true;
//
//        for (ParamReturner : params) {
//            if (first) {
//                first = false;
//            } else {
//                result.append("&");
//            }
//
//            result.append(URLEncoder.encode(getParam(), "UTF-8"));
//            result.append("=");
//        }
//
//        return result.toString();
//    }

}`

**Comment by BeepDroid** [comment]
**Notes from Development**

- Code was reviewed by me before posting and pushing, no errors observed aside from the referencing error mentioned above. We did talk about the possible integration of the commented segment, and decided to keep it until communicating with UI/UX. 
- Arrays have come up in discussion numerous times, which will be figured during further implementation. We were between using the commented code or just creating the array all at once. 
- Noted that a List would probably be more useful for the Grocery List implementation, a note to keep for later development. 

*This serves as just general note taking from our discussions together, information and passive observation that may be useful in the future.*

**Comment by BeepDroid** [comment]
Issue has been resolved, errors sorted and code posted.

**Comment by IanTDuncan** [comment]
### SearchResult Code for Meal Planner
**Description:** This is code that returns search results based on the documentation provided by Edamam Meal Planner API. Contains 4 classes: SearchResult, Hit, NutritionInfo, and Nutrients
- Errors: N/A

**Steps To Reproduce:**

1. Create the aforementioned Java Classes
2. Add any necessary dependencies to the build.gradle.kts class
3. Import the aforementioned dependencies into the Java Classes that require them
4. Create the constructors, getters, and setters for each of the classes
5. In the "Hit" class, add a class to get the total amount of nutrients
6. Additionally you will have to adjust the NutrientInfo class based on what nutrients your obtaining/showing in your search results

**Expected vs Actual Behavior:** 

- Expected Behavior: The expected behavior is to recipe information and anything related
- Actual Behavior: N/A

**Code Snippets**
### SearchResult:
`package com.example.mealtime1.APIs;

import java.util.List;

class SearchResult {
    private int from;
    private int to;
    private int count;
    private List<Hit> hits;

    public SearchResult(int from, int to, int count, List<Hit> hits) {
        this.from = from;
        this.to = to;
        this.count = count;
        this.hits = hits;
    }

    public int getFrom() {
        return from;
    }

    public void setFrom(int from) {
        this.from = from;
    }

    public int getTo() {
        return to;
    }

    public void setTo(int to) {
        this.to = to;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public List<Hit> getHits() {
        return hits;
    }

    public void setHits(List<Hit> hits) {
        this.hits = hits;
    }
}`

### Hit:
`package com.example.mealtime1.APIs;

import java.util.List;

public class Hit {
    private String recipeName;
    private String ingredients;
    private String instructions;
    private List<Nutrient> totalNutrients;
    private List<Nutrient> totalDaily;

    public Hit(String recipeName, String ingredients, String instructions, List<Nutrient> totalNutrients, List<Nutrient> totalDaily) {
        this.recipeName = recipeName;
        this.ingredients = ingredients;
        this.instructions = instructions;
        this.totalNutrients = totalNutrients;
        this.totalDaily = totalDaily;
    }

    public String getRecipeName() {
        return recipeName;
    }

    public void setRecipeName(String recipeName) {
        this.recipeName = recipeName;
    }

    public String getIngredients() {
        return ingredients;
    }

    public void setIngredients(String ingredients) {
        this.ingredients = ingredients;
    }

    public String getInstructions() {
        return instructions;
    }

    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    public List<Nutrient> getTotalNutrients() {
        return totalNutrients;
    }

    public void setTotalNutrients(List<Nutrient> totalNutrients) {
        this.totalNutrients = totalNutrients;
    }

    public List<Nutrient> getTotalDaily() {
        return totalDaily;
    }

    public void setTotalDaily(List<Nutrient> totalDaily) {
        this.totalDaily = totalDaily;
    }

    public NutritionInfo calculateOverallNutrition() {
        double calories = 0;
        double protein = 0;
        double carbohydrates = 0;
        double fats = 0;

        for (Nutrient nutrient : totalNutrients) {
            switch (nutrient.getCode()) {
                case "ENERC_KCAL":
                    calories += nutrient.getAmount();
                    break;
                case "PROCNT":
                    protein += nutrient.getAmount();
                    break;
                case "CHOCDF":
                    carbohydrates += nutrient.getAmount();
                    break;
                case "FAT":
                    fats += nutrient.getAmount();
                    break;
                // Room for more nutrients/cases
            }
        }

        return new NutritionInfo(calories, protein, carbohydrates, fats);
    }
}
`

### Nutrient:
package com.example.mealtime1.APIs;

public class Nutrient {
    private String code;
    private String name;
    private double amount;
    private String unit;

    public Nutrient(String code, String name, double amount, String unit) {
        this.code = code;
        this.name = name;
        this.amount = amount;
        this.unit = unit;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }
}

### NutritionInfo:
`package com.example.mealtime1.APIs;

class NutritionInfo {
    private double calories;
    private double protein;
    private double carbohydrates;
    private double fats;

    public NutritionInfo(double calories, double protein, double carbohydrates, double fats) {
        this.calories = calories;
        this.protein = protein;
        this.carbohydrates = carbohydrates;
        this.fats = fats;
    }

    public double getCalories() {
        return calories;
    }

    public void setCalories(double calories) {
        this.calories = calories;
    }

    public double getProtein() {
        return protein;
    }

    public void setProtein(double protein) {
        this.protein = protein;
    }

    public double getCarbohydrates() {
        return carbohydrates;
    }

    public void setCarbohydrates(double carbohydrates) {
        this.carbohydrates = carbohydrates;
    }

    public double getFats() {
        return fats;
    }

    public void setFats(double fats) {
        this.fats = fats;
    }
}
`

**Comment by aaleksandraristic** [comment]
@IanTDuncan Hey Ian, could you please put the formatted comment at the beginning of the issue (header or description section) so it will pop up on the top when we open the issue. That is one thing that he wanted us to do, so if you can please change that. Thank you!

**Comment by aaleksandraristic** [comment]
Also could you please update the due date in the roadmap for this issue? Thanks

**Comment by IanTDuncan** [comment]
@aaleksandraristic Will do forgot to do it last night, but will complete it before class

**Comment by aaleksandraristic** [comment]
Okay, sounds good, thank you!

**Comment by IanTDuncan** [comment]
@aaleksandraristic I updated the completion date for this issue and put it at the end of the month

**Comment by aaleksandraristic** [comment]
@IanTDuncan @BeepDroid 
Hey guys, just quick check about what's going on with edamam API, should we go and switch to Spoonacular?

Also if we're keeping this issue open, we should put it in a MVP milestone and update a due date.

**Comment by IanTDuncan** [comment]
@aaleksandraristic I'm closing this issue and all relevant issues due to us switching to Spoonacular if that's okay?
