### ISSUE TITLE
Backend Development - Privacy Policy

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#85]
Once Kerrigan is done with creating the privacy policy i will add it to the manifest and make sure the logic is correct for the popup

**Comment by Cade5480** [comment]
- [ ] Add Privacy Policy to Manifest
- [ ] Add logic

**Comment by aaleksandraristic** [comment]
I have extended the due date to tomorrow 2/14/2024!

**Comment by BeepDroid** [comment]
Meeting notes regarding this issue (Meeting Date: 2/12/2024):

- Cade and I reviewed Privacy Policy document, typos fixed, and it is now ready for inclusion. 
- Logic regarding this document was discussed as being the first pop-up upon access, with a check event at the bottom to show the user has read and agreed that they understood the clauses listed in the policy. 

End of relevant notes regarding this issue.

**Comment by aaleksandraristic** [comment]
Sorry, same for this issue -> just checking how's this issue going. Could you please post the description and current progress on this issue in the format that the professor gave us? Thank you!!

**Comment by Cade5480** [comment]
Everything is going good! I finished it yesterday, so I was adding the privacy policy and I had to create the logic for the button click on the about page and also adding it to the manifest.

  <activity android:name=".AccountAboutActivity" android:label="About" android:theme="@style/Theme.MealTime1" />

 buttonAbout.setOnClickListener { val intent = Intent(this, AccountAboutActivity::class.java) startActivity(intent) }

After that i went ahead and added the logic to be able to be taken to the URL where you can see our terms and conditions

 buttonPrivacyPolicy.setOnClickListener {
            val url = "https://publuu.com/flip-book/403736/913836"
            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(url))
            startActivity(intent)
        }
