### ISSUE TITLE
Backend Development - Terms and Conditions

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#86]
Once Kerrigan is done with creating the terms and conditions i will add it to the manifest and make sure the logic is correct for the popup

**Comment by Cade5480** [comment]
**Ticket # 1**

- [ ] Add Terms and Conditions to Manifest

- [ ] Add logic

**Comment by aaleksandraristic** [comment]
I have extended the due date to tomorrow 2/14/2024

**Comment by BeepDroid** [comment]
Meeting notes regarding this issue (Meeting Date: 2/12/2024): 

- Cade and I reviewed the Terms and Conditions document together and discussed formatting possiblitles. 
- For the backend development, we agreed that this particular document could be accessible through the "About" section in the Accounts page on the App. 
- The access would be through a PDF link to the aforementioned document, which we did discover you could download as is from the Google doc file. 

End of relevant notes.

**Comment by aaleksandraristic** [comment]
Hey Cade, just checking how's this issue going. Could you please post the description and current progress on this issue in the format that the professor gave us? Thank you!!

**Comment by Cade5480** [comment]
Everything is going good! I finished it yesterday, so I was adding the terms and conditions and I had to create the logic for the button click on the about page and also adding it to the manifest.

` 
        <activity
            android:name=".AccountAboutActivity"
            android:label="About"
            android:theme="@style/Theme.MealTime1" />`

` buttonAbout.setOnClickListener {
            val intent = Intent(this, AccountAboutActivity::class.java)
            startActivity(intent)
        }`

After that i went ahead and added the logic to be able to be taken to the URL where you can see our terms and conditions

` buttonForTerms.setOnClickListener {
            val url = "https://publuu.com/flip-book/403736/913832"
            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(url))
            startActivity(intent)
        }`
