### ISSUE TITLE
UI/UX - grocery_list_activity.xml

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#87]
Created xml page.

**Comment by bdshanks-28** [comment]
Worked on the baseline Kerry created, cleaned up activity and added attribution to edaman api since it is one of the few major pages that will use it.

**Comment by aaleksandraristic** [comment]
Hey Brandon, same here lol  I see that this issue is marked as done in the roadmap, should I close this issue?

**Comment by bdshanks-28** [comment]
Yes let me post the final code since I missed on using the correct format when this issue was created.

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    
    <TextView
        android:id="@+id/textViewGroceryListTitle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_marginStart="16dp"
        android:layout_marginTop="30dp"
        android:text="Grocery List"
        android:textSize="24sp" />

    
    <ListView
        android:id="@+id/listViewGroceryItems"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/textViewGroceryListTitle"
        android:layout_marginTop="20dp"
        android:layout_marginBottom="75dp" />


    <ImageView
        android:id="@+id/imageView"
        android:layout_width="250dp"
        android:layout_height="62dp"
        android:layout_alignParentBottom="true"
        android:src="@drawable/edamam_badge_transparent" />

    
    <Button
        android:id="@+id/buttonBackToMainMenu"
        android:layout_width="111dp"
        android:layout_height="50dp"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:layout_marginStart="10dp"
        android:layout_marginTop="16dp"
        android:layout_marginEnd="20dp"
        android:layout_marginBottom="20dp"
        android:text="Back" />

</RelativeLayout>
