### ISSUE TITLE
UI/UX - generate_meal_activity

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#89]
Created page and looked over the basics Kerry put down. Already planning out what will change and where to put the edaman attribution.

**Comment by bdshanks-28** [comment]
CURRENT CODE after opening issue:

<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    
    <Button
        android:id="@+id/buttonBackToMainMenu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Back"
        android:layout_alignParentTop="true"
        android:layout_alignParentStart="true"
        android:layout_margin="16dp"/>

    
    <EditText
        android:id="@+id/editTextCostLimit"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonBackToMainMenu"
        android:layout_marginTop="20dp"
        android:hint="Cost Limit"
        android:minHeight="48dp" />

    
    <EditText
        android:id="@+id/editTextCalorieLimit"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCostLimit"
        android:layout_marginTop="20dp"
        android:hint="Calorie Limit"
        android:minHeight="48dp" />

    

    <TextView
        android:id="@+id/textViewExclude"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCalorieLimit"
        android:layout_marginTop="119dp"
        android:text="Exclude" />

    <TextView
        android:id="@+id/textViewLimit"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCalorieLimit"
        android:layout_marginTop="20dp"
        android:layout_marginStart="20dp"
        android:text="Limit" />

    

    <Spinner
        android:id="@+id/spinnerExclude"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/textViewExclude"
        android:layout_marginTop="38dp"
        android:minHeight="48dp" />


    <Spinner
        android:id="@+id/spinnerLimit"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/textViewLimit"
        android:layout_marginStart="20dp"
        android:layout_marginTop="4dp"
        android:minHeight="48dp" />

    
    <EditText
        android:id="@+id/editTextLimitAmount"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/spinnerLimit"
        android:layout_marginTop="133dp"
        android:hint="Limit Amount"
        android:minHeight="48dp" />

    
    <Button
        android:id="@+id/buttonSaveOptions"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextLimitAmount"
        android:layout_marginTop="7dp"
        android:text="Save these options" />

    <Button
        android:id="@+id/buttonGenerateMeal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonSaveOptions"
        android:layout_marginTop="72dp"
        android:text="Generate Meal!" />

</RelativeLayout>

**Comment by bdshanks-28** [comment]
Add the attribution to edaman api and move the back button to the top left corner.

**Comment by aaleksandraristic** [comment]
Sounds good, no problem! I will move the due date to tomorrow

**Comment by bdshanks-28** [comment]
Just finished.

<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    
    <Button
        android:id="@+id/buttonBackToMainMenu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Back"
        android:layout_alignParentTop="true"
        android:layout_alignParentStart="true"
        android:layout_margin="16dp"/>

    
    <EditText
        android:id="@+id/editTextCostLimit"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonBackToMainMenu"
        android:layout_marginTop="20dp"
        android:hint="Cost Limit"
        android:minHeight="48dp" />

    
    <EditText
        android:id="@+id/editTextCalorieLimit"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCostLimit"
        android:layout_marginTop="20dp"
        android:hint="Calorie Limit"
        android:minHeight="48dp" />

    

    <TextView
        android:id="@+id/textViewExclude"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCalorieLimit"
        android:layout_marginTop="119dp"
        android:text="Exclude" />

    <TextView
        android:id="@+id/textViewLimit"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCalorieLimit"
        android:layout_marginTop="20dp"
        android:layout_marginStart="20dp"
        android:text="Limit" />

    

    <Spinner
        android:id="@+id/spinnerExclude"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/textViewExclude"
        android:layout_marginTop="38dp"
        android:minHeight="48dp" />


    <Spinner
        android:id="@+id/spinnerLimit"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/textViewLimit"
        android:layout_marginStart="20dp"
        android:layout_marginTop="4dp"
        android:minHeight="48dp" />

    
    <EditText
        android:id="@+id/editTextLimitAmount"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/spinnerLimit"
        android:layout_marginTop="133dp"
        android:hint="Limit Amount"
        android:minHeight="48dp" />

    
    <Button
        android:id="@+id/buttonSaveOptions"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextLimitAmount"
        android:layout_marginTop="7dp"
        android:text="Save these options" />

    <Button
        android:id="@+id/buttonGenerateMeal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextLimitAmount"
        android:layout_marginLeft="270dp"
        android:layout_marginTop="7dp"
        android:text="Generate Meal!" />

    <ImageView
        android:id="@+id/imageView2"
        android:layout_width="353dp"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonGenerateMeal"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="50dp"
        android:src="@drawable/edamam_badge_transparent" />

</RelativeLayout>
