### ISSUE TITLE
UI/UX - main_menu_activity.xml

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#90]
Generated page and placed some basic buttons (back, generate meal leading to generate_meal_activity.xml, grocery list leading to grocery_list_activity.xml, my account leading to account information, and my bookmarks going to mookmars_activity.xml) to have an idea of what functions it will do and where to go from here.

**Comment by aaleksandraristic** [comment]
Hey Brandon, just to check is this issue done since the deadline was Feb 9th?

If so, please provide us code and explanation of what you have done and close the issue.

**Comment by bdshanks-28** [comment]
Adjusted buttons, need feedback on locations.

Code changes: 
Back button
`    <Button
        android:id="@+id/buttonBack"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:layout_marginLeft="-100dp"
        android:layout_marginTop="-350dp"
        android:text="Back" />`

Generate Meal button
`
 <Button
        android:id="@+id/buttonGenerateMeal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonBack"
        android:layout_marginTop="150dp"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="Generate My Meal" />
`

Grocery List button
`
ndroid:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonGenerateMeal"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="Grocery List" />
`

My Bookmarks button
`
    <Button
        android:id="@+id/buttonMyBookmarks"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonGroceryList"
        android:layout_marginTop="10dp"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="My Bookmarks" />
`

My Account button
`
<Button
        android:id="@+id/buttonMyAccount"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/buttonMyBookmarks"
        android:layout_marginTop="80dp"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="My Account" />
`

Issues:
Ran into trouble moving buttons freely around in the UI version of relative layout.

Solution:
Changed to purely adjusting settings and pixel distance in the code to check back in the preview of it.

**Comment by bdshanks-28** [comment]
`
![image](https://github.com/IanTDuncan/MealTime/assets/143129575/056aca2f-5db7-4e8a-b015-4c75b0096224)
`

**Comment by bdshanks-28** [comment]
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center">

    
    <Button
        android:id="@+id/buttonBack"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:layout_marginLeft="-100dp"
        android:layout_marginTop="-350dp"
        android:text="Back" />

    
    <Button
        android:id="@+id/buttonGenerateMeal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonBack"
        android:layout_marginTop="150dp"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="Generate My Meal" />


    
    <Button
        android:id="@+id/buttonGroceryList"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonGenerateMeal"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="Grocery List" />

    

    <Button
        android:id="@+id/buttonMyBookmarks"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonGroceryList"
        android:layout_marginTop="10dp"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="My Bookmarks" />

    
    <Button
        android:id="@+id/buttonMyAccount"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/buttonMyBookmarks"
        android:layout_marginTop="80dp"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="My Account" />

</RelativeLayout>

**Comment by aaleksandraristic** [comment]
@bdshanks-28  just checking when are you expecting to get done with this issue so I can change it in the roadmap?

**Comment by bdshanks-28** [comment]
Just finished.

<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    
    <Button
        android:id="@+id/buttonBackToMainMenu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Back"
        android:layout_alignParentTop="true"
        android:layout_alignParentStart="true"
        android:layout_margin="16dp"/>

    
    <EditText
        android:id="@+id/editTextCostLimit"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonBackToMainMenu"
        android:layout_marginTop="20dp"
        android:hint="Cost Limit"
        android:minHeight="48dp" />

    
    <EditText
        android:id="@+id/editTextCalorieLimit"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCostLimit"
        android:layout_marginTop="20dp"
        android:hint="Calorie Limit"
        android:minHeight="48dp" />

    

    <TextView
        android:id="@+id/textViewExclude"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCalorieLimit"
        android:layout_marginTop="119dp"
        android:text="Exclude" />

    <TextView
        android:id="@+id/textViewLimit"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextCalorieLimit"
        android:layout_marginTop="20dp"
        android:layout_marginStart="20dp"
        android:text="Limit" />

    

    <Spinner
        android:id="@+id/spinnerExclude"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/textViewExclude"
        android:layout_marginTop="38dp"
        android:minHeight="48dp" />


    <Spinner
        android:id="@+id/spinnerLimit"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/textViewLimit"
        android:layout_marginStart="20dp"
        android:layout_marginTop="4dp"
        android:minHeight="48dp" />

    
    <EditText
        android:id="@+id/editTextLimitAmount"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/spinnerLimit"
        android:layout_marginTop="133dp"
        android:hint="Limit Amount"
        android:minHeight="48dp" />

    
    <Button
        android:id="@+id/buttonSaveOptions"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextLimitAmount"
        android:layout_marginTop="7dp"
        android:text="Save these options" />

    <Button
        android:id="@+id/buttonGenerateMeal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/editTextLimitAmount"
        android:layout_marginLeft="270dp"
        android:layout_marginTop="7dp"
        android:text="Generate Meal!" />

    <ImageView
        android:id="@+id/imageView2"
        android:layout_width="353dp"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonGenerateMeal"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="50dp"
        android:src="@drawable/edamam_badge_transparent" />

</RelativeLayout>

**Comment by bdshanks-28** [comment]
Reopened due to mixing issues.

Description: Ran into formatting issues with location of the buttons on the preview of the xml page.

Steps to reproduce: Simply try and drag the visual aspects of the buttons on the screen.

Expected vs Actual behavior: I expected the buttons to move where I put them. What actually happened was they rubber banded back to their original location or to a different parent object to be placed above them.

Code: 

<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center">

    

    


    

    <Button
        android:id="@+id/buttonBack"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:layout_marginStart="-100dp"
        android:layout_marginTop="-160dp"
        android:text="Back" />

    <Button
        android:id="@+id/buttonGenerateMeal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="Generate My Meal" />

    <Button
        android:id="@+id/buttonGroceryList"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonGenerateMeal"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="Grocery List" />

    

    <Button
        android:id="@+id/buttonMyBookmarks"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/buttonGroceryList"
        android:layout_marginTop="10dp"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="My Bookmarks" />

    
    <Button
        android:id="@+id/buttonMyAccount"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/buttonMyBookmarks"
        android:layout_marginTop="40dp"
        android:layout_marginBottom="20dp"
        android:padding="16dp"
        android:text="My Account" />

</RelativeLayout>

Issue Resolution: Tried turning off autoconnection to parent option but that did not provide any changes. Eventually I switched to purely editing the xml code which resolved the issue.
