### ISSUE TITLE
UI/UX - privacy_security_policy_action.xml

### ISSUE THREAD

**Issue by bdshanks-28** [IanTDuncan/MealTime#91]
Created the xml file and it is currently a blank page to work with from there. Planning to implement a scrollview to put the policy statements there.

**Comment by bdshanks-28** [comment]
Extended due date due to not having time to work on this. Plan to add a scrollview for the privacy policy page.

**Comment by bdshanks-28** [comment]
This issue might be merged with account_about_activity.xml since that is where the buttons for privacy and security policy went.

**Comment by aaleksandraristic** [comment]
Hey Brandon, how is this issue going? I think due was yesterday, so please update the due date if you're still working on it. Could you please post the description and current progress on this issue in the format that the professor gave us? Thank you!!

**Comment by bdshanks-28** [comment]
Yes we should go ahead and close this. We can reopen it if needed.
