### ISSUE TITLE
AndoidXML Manifest - Backend Development

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#92]
I need to add the rest of the classes to the xml manifest so we can get the correct popups on button click and logic to all of their back buttons.

**Comment by Cade5480** [comment]
Ticket
- [ ] Add all remaining classes to the manifest
- [ ] Add logic to all button clicks

**Comment by aaleksandraristic** [comment]
@Cade5480 Could you please put the formatted comment in the header or description section of the issue? Thank you!

**Comment by aaleksandraristic** [comment]
@Cade5480 I am sorry for this late comment. Your formatted comment should be right at the beginning of the issue (in the description section). Could you please just move it to the top?
