### ISSUE TITLE
XML File Cleanup

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#95]
Description
-----------------------------------
Currently adding in all issues of creation of pages. Going to add in issues of button/text box/scroll view creation next. Then an issue pertaining to redundancy, then an issue relating to removing redundant files.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

We are using Android Studio IDE.

For Issue Resolution:
------------------------------

Looking into created issues once issues are caught up.

For Investigations/Research:
------------------------------------------

N/A

Current Status: 
------------------------

Completed

**Comment by bdshanks-28** [comment]
Description
-----------------------------------
Currently adding in all issues of creation of pages. Going to add in issues of button/text box/scroll view creation next. Then an issue pertaining to redundancy, then an issue relating to removing redundant files.

Steps to Reproduce: 
-------------------------------

N/A

Expected vs. Actual Behavior: 
-------------------------------------------

N/A

Code Snippets: 
-----------------------------

N/A

Environment Details: 
------------------------------

We are using Android Studio IDE.

For Issue Resolution:
------------------------------

Looking into created issues once issues are caught up.

For Investigations/Research:
------------------------------------------

N/A

Current Status: 
------------------------

In progress

**Comment by bdshanks-28** [comment]
Please check on #108 for more details.

**Comment by bdshanks-28** [comment]
Please check on issue #114 for more details.

**Comment by bdshanks-28** [comment]
Please check on issue #115 for more details.

**Comment by aaleksandraristic** [comment]
Good organization of issues, nicely done!

**Comment by aaleksandraristic** [comment]
Hey guys, just to let you know that I have moved the formatted comment into the issue's header (description section).

**Comment by bdshanks-28** [comment]
I think we can close this issue for now @Cade5480 and @aaleksandraristic.

**Comment by Cade5480** [comment]
I still need to update this format and then I will close this issue later this afternoon
